var getDataIntegration  = {
  "message": "Successfully get candidate list",
  "data": {
      "candidates": [
          {
              "candidate_id": 15605,
              "job_application_id": 15467,
              "company_id": 10,
              "job_id": 8130,
              "job_position_id": 487192,
              "job_position_name": "Job Tester Ai",
              "branch_id": 137,
              "branch_name": "DEPOK",
              "organization_id": 138266,
              "organization_name": "B1",
              "candidate_name": "New Joiner 02 tue 4 feb 25",
              "first_name": "New Joiner 02",
              "last_name": "tue 4 feb 25",
              "email": "newjoiner02@yopmail.com",
              "phone_number": "081208120812",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "mekari_image_ehw5n4.png",
              "applied_date": "2025-02-04T07:05:07.485345Z",
              "status": 1,
              "source": 1,
              "source_name": "Career Page",
              "last_stage_id": 9299,
              "last_stage_name": "Candidate Review !@#🥳",
              "hiring_stage_id": 37,
              "hiring_stage_status": 0,
              "hired_date": "2025-02-16",
              "joining_date": null,
              "new_joiner_status": "Yes to fill",
              "new_joiner_expired_date": "2025-02-11"
          },
          {
              "candidate_id": 15604,
              "job_application_id": 15466,
              "company_id": 10,
              "job_id": 8130,
              "job_position_id": 487192,
              "job_position_name": "Job Tester Ai",
              "branch_id": 137,
              "branch_name": "DEPOK",
              "organization_id": 138266,
              "organization_name": "B1",
              "candidate_name": "New Candidate 01 4 feb 25",
              "first_name": "New Candidate 01",
              "last_name": "4 feb 25",
              "email": "newcandidate01@yopmail.com",
              "phone_number": "081208120812",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "mekari_image_2RMFCb.png",
              "applied_date": "2025-02-04T06:35:26.468265Z",
              "status": 1,
              "source": 1,
              "source_name": "Career Page",
              "last_stage_id": 9223,
              "last_stage_name": "Offer Accepted",
              "hiring_stage_id": 37,
              "hiring_stage_status": 0,
              "hired_date": null,
              "joining_date": null,
              "new_joiner_status": "Yes to fill",
              "new_joiner_expired_date": "2025-02-11"
          },
          {
              "candidate_id": 15528,
              "job_application_id": 15390,
              "company_id": 10,
              "job_id": 7439,
              "job_position_id": 296969,
              "job_position_name": "Admin FTX",
              "branch_id": 0,
              "branch_name": "PT. Digital Talenta Test",
              "organization_id": 167682,
              "organization_name": "A2New Org",
              "candidate_name": "asd asd",
              "first_name": "asd",
              "last_name": "asd",
              "email": "asd@yopmail.com",
              "phone_number": "082121930122",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "sad_tom_k4Nd1C_KxSugE.jpg",
              "applied_date": "2025-02-03T08:23:45.434547Z",
              "status": 1,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 9170,
              "last_stage_name": "Candidate Review !@#🥳",
              "hiring_stage_id": 37,
              "hiring_stage_status": 0,
              "hired_date": "2025-02-16",
              "joining_date": null,
              "new_joiner_status": "Yes to fill",
              "new_joiner_expired_date": "2025-02-11"
          },
          {
              "candidate_id": 15514,
              "job_application_id": 15376,
              "company_id": 10,
              "job_id": 8122,
              "job_position_id": 348702,
              "job_position_name": "HR",
              "branch_id": 805,
              "branch_name": "Jakarta",
              "organization_id": 138266,
              "organization_name": "B1",
              "candidate_name": "gerrard arhdnana",
              "first_name": "gerrard",
              "last_name": "arhdnana",
              "email": "arief@mail.co",
              "phone_number": "081230914142",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "",
              "applied_date": "2025-02-03T06:43:30.204608Z",
              "status": 0,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 9171,
              "last_stage_name": "Personality Test c*(0🥲",
              "hiring_stage_id": 39914,
              "hiring_stage_status": 0,
              "hired_date": null,
              "joining_date": null,
              "new_joiner_status": "Form not sent",
              "new_joiner_expired_date": null
          },
          {
              "candidate_id": 15259,
              "job_application_id": 15121,
              "company_id": 10,
              "job_id": 7063,
              "job_position_id": 487192,
              "job_position_name": "Job Tester Ai",
              "branch_id": 805,
              "branch_name": "Jakarta",
              "organization_id": 174261,
              "organization_name": "Tester AI",
              "candidate_name": "Test 02 31 Jan 2025",
              "first_name": "Test 02",
              "last_name": "31 Jan 2025",
              "email": "test0231jan2025@mail.com",
              "phone_number": "081208120812",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "mekari_image_CxShwB.png",
              "applied_date": "2025-01-31T04:56:13.065904Z",
              "status": 0,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 9110,
              "last_stage_name": "Personality Test c*(0🥲",
              "hiring_stage_id": 32099,
              "hiring_stage_status": 0,
              "hired_date": null,
              "joining_date": null,
              "new_joiner_status": "Form not sent",
              "new_joiner_expired_date": null
          },
          {
              "candidate_id": 15258,
              "job_application_id": 15120,
              "company_id": 10,
              "job_id": 7439,
              "job_position_id": 296969,
              "job_position_name": "Admin FTX",
              "branch_id": 0,
              "branch_name": "PT. Digital Talenta Test",
              "organization_id": 167682,
              "organization_name": "A2New Org",
              "candidate_name": "Test 01 31 Jan 2025",
              "first_name": "Test 01",
              "last_name": "31 Jan 2025",
              "email": "test0131jan2025@mail.com",
              "phone_number": "081208120812",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "mekari_image_sw6n4F.png",
              "applied_date": "2025-01-31T04:51:17.599149Z",
              "status": 0,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 9109,
              "last_stage_name": "Candidate Review !@#🥳",
              "hiring_stage_id": 33326,
              "hiring_stage_status": 0,
              "hired_date": null,
              "joining_date": null,
              "new_joiner_status": "Form not sent",
              "new_joiner_expired_date": null
          },
          {
              "candidate_id": 15112,
              "job_application_id": 14974,
              "company_id": 10,
              "job_id": 7439,
              "job_position_id": 296969,
              "job_position_name": "Admin FTX",
              "branch_id": 0,
              "branch_name": "PT. Digital Talenta Test",
              "organization_id": 167682,
              "organization_name": "A2New Org",
              "candidate_name": "Rizki Nida Chaerulsyah",
              "first_name": "Rizki",
              "last_name": "Nida Chaerulsyah",
              "email": "rizki.nc@yopmail.com",
              "phone_number": "085218849641",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "uploads_custom-form_KDNuRFQC3JV8mqQdsHrxe51rT4zjl_vs_0brrIP.png",
              "applied_date": "2025-01-30T07:45:10.349495Z",
              "status": 1,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 0,
              "last_stage_name": "Hired Candidate 💻()90",
              "hiring_stage_id": 37,
              "hiring_stage_status": 0,
              "hired_date": null,
              "joining_date": null,
              "new_joiner_status": "Yes to fill",
              "new_joiner_expired_date": "2025-02-06"
          },
          {
              "candidate_id": 14825,
              "job_application_id": 14687,
              "company_id": 10,
              "job_id": 7366,
              "job_position_id": 309849,
              "job_position_name": "Head Chef",
              "branch_id": 805,
              "branch_name": "Jakarta",
              "organization_id": 167687,
              "organization_name": "Delta Organization",
              "candidate_name": "Arief  Ardhan",
              "first_name": "Arief ",
              "last_name": "Ardhan",
              "email": "ariefsalah@yopmail.co",
              "phone_number": "08123091409",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "jpg_sample_wfT7iz.jpg",
              "applied_date": "2025-01-30T03:32:16.082531Z",
              "status": 1,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 9301,
              "last_stage_name": "Candidate Review !@#🥳",
              "hiring_stage_id": 37,
              "hiring_stage_status": 0,
              "hired_date": "2025-02-24",
              "joining_date": null,
              "new_joiner_status": "Yes to fill",
              "new_joiner_expired_date": "2025-02-11"
          },
          {
              "candidate_id": 14732,
              "job_application_id": 14594,
              "company_id": 10,
              "job_id": 7063,
              "job_position_id": 487192,
              "job_position_name": "Job Tester Ai",
              "branch_id": 805,
              "branch_name": "Jakarta",
              "organization_id": 174261,
              "organization_name": "Tester AI",
              "candidate_name": "arief ardhan",
              "first_name": "arief",
              "last_name": "ardhan",
              "email": "arief@yopmail.co",
              "phone_number": "081230914091",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "Screenshot_2025-01-28_at_10.45.03_HWOrhc.png",
              "applied_date": "2025-01-28T04:17:57.645888Z",
              "status": 1,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 9063,
              "last_stage_name": "Offer Accepted",
              "hiring_stage_id": 37,
              "hiring_stage_status": 0,
              "hired_date": null,
              "joining_date": null,
              "new_joiner_status": "Form not sent",
              "new_joiner_expired_date": null
          },
          {
              "candidate_id": 14531,
              "job_application_id": 14393,
              "company_id": 10,
              "job_id": 7018,
              "job_position_id": 486528,
              "job_position_name": "Alpha Senior QA",
              "branch_id": 137,
              "branch_name": "DEPOK",
              "organization_id": 10644,
              "organization_name": "Job Test",
              "candidate_name": "agung ap 230125",
              "first_name": "agung",
              "last_name": "ap 230125",
              "email": "agung.aprianto@mekari.com",
              "phone_number": "085710563507",
              "last_job_position": "",
              "last_company": "",
              "last_education": 0,
              "last_education_level": "No Qualification",
              "avatar": "IMG_0177_tLSIE2.jpg",
              "applied_date": "2025-01-23T12:55:08.953707Z",
              "status": 0,
              "source": 0,
              "source_name": "Manually Added",
              "last_stage_id": 8961,
              "last_stage_name": "Medical Checkup candidate",
              "hiring_stage_id": 31974,
              "hiring_stage_status": 1,
              "hired_date": null,
              "joining_date": null,
              "new_joiner_status": "Form not sent",
              "new_joiner_expired_date": null
          }
      ],
      "pagination": {
          "current_page": 1,
          "first_page_url": "https://api.mekari.io/v2/talenta-ppe/v3/recruitment/candidates?page=1",
          "from": 1,
          "last_page": 31,
          "last_page_url": "https://api.mekari.io/v2/talenta-ppe/v3/recruitment/candidates?page=31",
          "next_page_url": "https://api.mekari.io/v2/talenta-ppe/v3/recruitment/candidates?page=2",
          "path": "https://api.mekari.io/v2/talenta-ppe/v3/recruitment/candidates?",
          "per_page": 10,
          "prev_page_url": "",
          "to": 10,
          "total": 310
      }
  }
};

function _log(msg) {
  console.log(msg);
};

// Page Limit
var totalData = 0;
var limit = 100;
var listParameter = [];

var hitAPITalenta = {};

if (typeof hitAPITalenta === "object") {
    totalData = getDataIntegration.data.pagination.total;
};

console.log(totalData);

var totalPage = totalData / limit + 1;
var arrayPage = [];

for (i = 1; i < totalPage; i++) {
    var listParameter = {
        has_generate: false,
        page: i,
        limit: limit,
    };
    arrayPage.push(listParameter);
};

_log(arrayPage);