var getCandidate = [
  {
    stage_detail: [
      {
        feedback: "",
        result_id: {
          id: "ize5o3qVKTUGDLWu",
          name: "LULUS",
        },
        score: "100",
        stage_id: {
          id: "vlQhblAg19HpmH0U",
          name: "Psikotest",
        },
      },
      {
        feedback: "BAGUS",
        result_id: {
          id: "ize5o3qVKTUGDLWu",
          name: "LULUS",
        },
        score: "100",
        stage_id: {
          id: "ize93zK0gd5vDoYY",
          name: "Confirmatory Test",
        },
      },
    ],
  },
];

var stageDetail = [
  {
    feedback: "",
    result_id: {
      id: "ize5o3qVKTUGDLWu",
      name: "LULUS",
    },
    score: "100",
    stage_id: {
      id: "vlQhblAg19HpmH0U",
      name: "Psikotest",
    },
  },
  {
    feedback: "BAGUS",
    result_id: {
      id: "ize5o3qVKTUGDLWu",
      name: "LULUS",
    },
    score: "100",
    stage_id: {
      id: "ize93zK0gd5vDoYY",
      name: "Confirmatory Test",
    },
  },
  {
    feedback: "BAGUS",
    result_id: {
      id: "ize5o3qVKTUGDLWu",
      name: "LULUS",
    },
    score: 100,
    stage_id: {
      id: "ize93zK0gd5vDoYY",
      name: "Confirmatory Test",
    },
  },
];

var candidateStageIdMap = {};
for (var i = 0; i < getCandidate.length; i++) {
  var stageDetails = getCandidate[i].stage_detail || [];
  for (var j = 0; j < stageDetails.length; j++) {
    candidateStageIdMap[stageDetails[j].stage_id.id] = true;
  }
}

var encounteredStageIds = {};

var cleanStageDetail = [];
for (var k = 0; k < stageDetail.length; k++) {
  var stageIdValue = stageDetail[k].stage_id.id;

  if (candidateStageIdMap[stageIdValue]) {
    if (!encounteredStageIds[stageIdValue]) {
      encounteredStageIds[stageIdValue] = true;
      cleanStageDetail.push(stageDetail[k]);
    }
  } else {
    cleanStageDetail.push(stageDetail[k]);
  }
}

stageDetail = cleanStageDetail;

console.log(stageDetail);


var data = {
  "agama": "getCandidate.agama",
  "akreditasi_pendidikan_1": "getCandidate.akreditasi_pendidikan_1",
  "akreditasi_pendidikan_2": "getCandidate.akreditasi_pendidikan_2",
  "alamat_domisili": "getCandidate.alamat_domisili",
  "alamat_institusi_pendidikan_1": "getCandidate.alamat_institusi_pendidikan_1",
  "alamat_institusi_pendidikan_2": "getCandidate.alamat_institusi_pendidikan_2",
  "alamat_ktp": "getCandidate.alamat_ktp",
  "alamat_lembaga_pelatihan_1": "getCandidate.alamat_lembaga_pelatihan_1",
  "alamat_lembaga_pelatihan_2": "getCandidate.alamat_lembaga_pelatihan_2",
  "applied_job_position": "getCandidate.applied_job_position",
  "approved_by": "",
  "bahasa_1": "getCandidate.bahasa_1",
  "bahasa_2": "getCandidate.bahasa_2",
  "berat_badan": "getCandidate.berat_badan",
  "bidang_organisasi_1": "getCandidate.bidang_organisasi_1",
  "bidang_organisasi_2": "getCandidate.bidang_organisasi_2",
  "bidang_pelatihan_1": "getCandidate.bidang_pelatihan_1",
  "bidang_pelatihan_2": "getCandidate.bidang_pelatihan_2",
  "bidang_perusahaan_pengalaman_1": "getCandidate.bidang_perusahaan_pengalaman_1",
  "bidang_perusahaan_pengalaman_2": "getCandidate.bidang_perusahaan_pengalaman_2",
  "bulan_akhir_organisasi_1": "getCandidate.bulan_akhir_organisasi_1",
  "bulan_akhir_organisasi_2": "getCandidate.bulan_akhir_organisasi_2",
  "bulan_akhir_perusahaan_1": "getCandidate.bulan_akhir_perusahaan_1",
  "bulan_akhir_perusahaan_2": "getCandidate.bulan_akhir_perusahaan_2",
  "bulan_awal_organisasi_1": "getCandidate.bulan_awal_organisasi_1",
  "bulan_awal_organisasi_2": "getCandidate.bulan_awal_organisasi_2",
  "bulan_awal_perusahaan_1": "getCandidate.bulan_awal_perusahaan_1",
  "bulan_awal_perusahaan_2": "getCandidate.bulan_awal_perusahaan_2",
  "created_at": "",
  "created_by": "",
  "email": "getCandidate.email",
  "email_send_status": "'MENUNGGU'",
  "fakultas_pendidikan_1": "getCandidate.fakultas_pendidikan_1",
  "fakultas_pendidikan_2": "getCandidate.fakultas_pendidikan_2",
  "file_cv": "generateCV.data.url",
  "file_ijazah_pendidikan_terakhir": "getCandidate.file_ijazah_pendidikan_terakhir",
  "file_sertifikasi_1": "getCandidate.file_sertifikasi_1",
  "file_sertifikasi_2": "getCandidate.file_sertifikasi_2",
  "first_name": "getCandidate.first_name",
  "flow_status": "",
  "gaji_terakhir_perusahaan_1": "getCandidate.gaji_terakhir_perusahaan_1",
  "gaji_terakhir_perusahaan_2": "getCandidate.gaji_terakhir_perusahaan_2",
  "handphone_1": "getCandidate.handphone_1",
  "handphone_2": "getCandidate.handphone_2",
  "hubungan_kerabat_1": "getCandidate.hubungan_kerabat_1",
  "hubungan_kerabat_2": "getCandidate.hubungan_kerabat_2",
  "hubungan_kerabat_3": "getCandidate.hubungan_kerabat_3",
  "instansi_ayah": "getCandidate.instansi_ayah",
  "instansi_ibu": "getCandidate.instansi_ibu",
  "instansi_saudara_1": "getCandidate.instansi_saudara_1",
  "instansi_saudara_2": "getCandidate.instansi_saudara_2",
  "instansi_saudara_3": "getCandidate.instansi_saudara_3",
  "institusi_pendidikan_1": "getCandidate.institusi_pendidikan_1",
  "institusi_pendidikan_2": "getCandidate.institusi_pendidikan_2",
  "ipk_pendidikan_1": "getCandidate.ipk_pendidikan_1",
  "ipk_pendidikan_2": "getCandidate.ipk_pendidikan_2",
  "jabatan_akhir_perusahaan_1": "getCandidate.jabatan_akhir_perusahaan_1",
  "jabatan_akhir_perusahaan_2": "getCandidate.jabatan_akhir_perusahaan_2",
  "jabatan_awal_perusahaan_1": "getCandidate.jabatan_awal_perusahaan_1",
  "jabatan_awal_perusahaan_2": "getCandidate.jabatan_awal_perusahaan_2",
  "jabatan_organisasi_1": "getCandidate.jabatan_organisasi_1",
  "jabatan_organisasi_2": "getCandidate.jabatan_organisasi_2",
  "jenis_kelamin": "getCandidate.jenis_kelamin",
  "jenis_kelamin_kerabat_1": "getCandidate.jenis_kelamin_kerabat_1",
  "jenis_kelamin_kerabat_2": "getCandidate.jenis_kelamin_kerabat_2",
  "jenis_kelamin_kerabat_3": "getCandidate.jenis_kelamin_kerabat_3",
  "jenis_kelamin_saudara_1": "getCandidate.jenis_kelamin_saudara_1",
  "jenis_kelamin_saudara_2": "getCandidate.jenis_kelamin_saudara_2",
  "jenis_kelamin_saudara_3": "getCandidate.jenis_kelamin_saudara_3",
  "jenis_perusahaan_pengalaman_1": "getCandidate.jenis_perusahaan_pengalaman_1",
  "jenis_perusahaan_pengalaman_2": "getCandidate.jenis_perusahaan_pengalaman_2",
  "jenjang_pendidikan_1": "getCandidate.jenjang_pendidikan_1",
  "jenjang_pendidikan_2": "getCandidate.jenjang_pendidikan_2",
  "job_titkle_kerabat_1": "getCandidate.job_titkle_kerabat_1",
  "job_titkle_kerabat_3": "getCandidate.job_titkle_kerabat_3",
  "job_title_kerabat_2": "getCandidate.job_title_kerabat_2",
  "jumlah_kantor_cabang_perusahaan_1": "getCandidate.jumlah_kantor_cabang_perusahaan_1",
  "jumlah_kantor_cabang_perusahaan_2": "getCandidate.jumlah_kantor_cabang_perusahaan_2",
  "jumlah_karyawan_perusahaan_1": "getCandidate.jumlah_karyawan_perusahaan_1",
  "jumlah_karyawan_perusahaan_2": "getCandidate.jumlah_karyawan_perusahaan_2",
  "jurusan_pendidikan_1": "getCandidate.jurusan_pendidikan_1",
  "jurusan_pendidikan_2": "getCandidate.jurusan_pendidikan_2",
  "kabupaten_domisili": "getCandidate.kabupaten_domisili",
  "kabupaten_institusi_pendidikan_1": "getCandidate.kabupaten_institusi_pendidikan_1",
  "kabupaten_institusi_pendidikan_2": "getCandidate.kabupaten_institusi_pendidikan_2",
  "kabupaten_ktp": "getCandidate.kabupaten_ktp",
  "kabupaten_lembaga_pelatihan_1": "getCandidate.kabupaten_lembaga_pelatihan_1",
  "kabupaten_lembaga_pelatihan_2": "getCandidate.kabupaten_lembaga_pelatihan_2",
  "kodepos_domisili": "getCandidate.kodepos_domisili",
  "kodepos_institusi_pendidikan_1": "getCandidate.kodepos_institusi_pendidikan_1",
  "kodepos_institusi_pendidikan_2": "getCandidate.kodepos_institusi_pendidikan_2",
  "kodepos_ktp": "getCandidate.kodepos_ktp",
  "kodepos_lembaga_pelatihan_1": "getCandidate.kodepos_lembaga_pelatihan_1",
  "kodepos_lembaga_pelatihan_2": "getCandidate.kodepos_lembaga_pelatihan_2",
  "ktp_valid_until": "getCandidate.ktp_valid_until",
  "last_name": "getCandidate.last_name",
  "lembaga_pelatihan_1": "getCandidate.lembaga_pelatihan_1",
  "lembaga_pelatihan_2": "getCandidate.lembaga_pelatihan_2",
  "nama_ayah": "getCandidate.nama_ayah",
  "nama_ibu": "getCandidate.nama_ibu",
  "nama_kerabat_1": "getCandidate.nama_kerabat_1",
  "nama_kerabat_2": "getCandidate.nama_kerabat_2",
  "nama_kerabat_3": "getCandidate.nama_kerabat_3",
  "nama_lengkap": "getCandidate.nama_lengkap",
  "nama_organisasi_1": "getCandidate.nama_organisasi_1",
  "nama_organisasi_2": "getCandidate.nama_organisasi_2",
  "nama_pelatihan_1": "getCandidate.nama_pelatihan_1",
  "nama_pelatihan_2": "getCandidate.nama_pelatihan_2",
  "nama_saudara_1": "getCandidate.nama_saudara_1",
  "nama_saudara_2": "getCandidate.nama_saudara_2",
  "nama_saudara_3": "getCandidate.nama_saudara_3",
  "nik": "getCandidate.nik",
  "no_ijazah_pendidikan_1": "getCandidate.no_ijazah_pendidikan_1",
  "no_ijazah_pendidikan_2": "getCandidate.no_ijazah_pendidikan_2",
  "no_kk": "getCandidate.no_kk",
  "pekerjaan_ayah": "getCandidate.pekerjaan_ayah",
  "pekerjaan_ibu": "getCandidate.pekerjaan_ibu",
  "pekerjaan_saudara_1": "getCandidate.pekerjaan_saudara_1",
  "pekerjaan_saudara_2": "getCandidate.pekerjaan_saudara_2",
  "pekerjaan_saudara_3": "getCandidate.pekerjaan_saudara_3",
  "period_id": "getCandidate.period_id",
  "period_id_text": "getCandidate.period_id_text",
  "pernah_toefl_ielts": "getCandidate.pernah_toefl_ielts",
  "perusahaan_pengalaman_1": "getCandidate.perusahaan_pengalaman_1",
  "perusahaan_pengalaman_2": "getCandidate.perusahaan_pengalaman_2",
  "photo_full_body": "getCandidate.photo_full_body",
  "photo_half_body": "getCandidate.photo_half_body",
  "photo_profile": "getCandidate.photo_profile",
  "pipeline_id": "getCandidate.pipeline_id",
  "provinsi_domisili": "getCandidate.provinsi_domisili",
  "provinsi_institusi_pendidikan_1": "getCandidate.provinsi_institusi_pendidikan_1",
  "provinsi_institusi_pendidikan_2": "getCandidate.provinsi_institusi_pendidikan_2",
  "provinsi_ktp": "getCandidate.provinsi_ktp",
  "provinsi_lembaga_pelatihan_1": "getCandidate.provinsi_lembaga_pelatihan_1",
  "provinsi_lembaga_pelatihan_2": "getCandidate.provinsi_lembaga_pelatihan_2",
  "punya_kerabat_bpjs": "getCandidate.punya_kerabat_bpjs",
  "status_kawin": "getCandidate.status_kawin",
  "status_lulus_pendidikan_1": "getCandidate.status_lulus_pendidikan_1",
  "status_lulus_pendidikan_2": "getCandidate.status_lulus_pendidikan_2",
  "tahun_akhir_organisasi_1": "getCandidate.tahun_akhir_organisasi_1",
  "tahun_akhir_organisasi_2": "getCandidate.tahun_akhir_organisasi_2",
  "tahun_akhir_perusahaan_1": "getCandidate.tahun_akhir_perusahaan_1",
  "tahun_akhir_perusahaan_2": "getCandidate.tahun_akhir_perusahaan_2",
  "tahun_awal_organisasi_1": "getCandidate.tahun_awal_organisasi_1",
  "tahun_awal_organisasi_2": "getCandidate.tahun_awal_organisasi_2",
  "tahun_awal_perusahaan_1": "getCandidate.tahun_awal_perusahaan_1",
  "tahun_awal_perusahaan_2": "getCandidate.tahun_awal_perusahaan_2",
  "tahun_mulai_pendidikan_1": "getCandidate.tahun_mulai_pendidikan_1",
  "tahun_mulai_pendidikan_2": "getCandidate.tahun_mulai_pendidikan_2",
  "tahun_pelatihan_1": "getCandidate.tahun_pelatihan_1",
  "tahun_pelatihan_2": "getCandidate.tahun_pelatihan_2",
  "tahun_selesai_pendidikan_1": "getCandidate.tahun_selesai_pendidikan_1",
  "tahun_selesai_pendidikan_2": "getCandidate.tahun_selesai_pendidikan_2",
  "tanggal_lahir": "getCandidate.tanggal_lahir",
  "tanggal_lahir_ayah": "getCandidate.tanggal_lahir_ayah",
  "tanggal_lahir_ibu": "getCandidate.tanggal_lahir_ibu",
  "tanggal_lahir_saudara_1": "getCandidate.tanggal_lahir_saudara_1",
  "tanggal_lahir_saudara_2": "getCandidate.tanggal_lahir_saudara_2",
  "tanggal_lahir_saudara_3": "getCandidate.tanggal_lahir_saudara_3",
  "telepon": "getCandidate.telepon",
  "tempat_lahir": "getCandidate.tempat_lahir",
  "tgl_lahir_kerabat_1": "getCandidate.tgl_lahir_kerabat_1",
  "tgl_lahir_kerabat_2": "getCandidate.tgl_lahir_kerabat_2",
  "tgl_lahir_kerabat_3": "getCandidate.tgl_lahir_kerabat_3",
  "tinggi_badan": "getCandidate.tinggi_badan",
  "tingkat_lisan_bahasa_1": "getCandidate.tingkat_lisan_bahasa_1",
  "tingkat_lisan_bahasa_2": "getCandidate.tingkat_lisan_bahasa_2",
  "tingkat_membaca_bahasa_1": "getCandidate.tingkat_membaca_bahasa_1",
  "tingkat_membaca_bahasa_2": "getCandidate.tingkat_membaca_bahasa_2",
  "tingkat_mendengar_bahasa_1": "getCandidate.tingkat_mendengar_bahasa_1",
  "tingkat_mendengar_bahasa_2": "getCandidate.tingkat_mendengar_bahasa_2",
  "tingkat_menulis_bahasa_1": "getCandidate.tingkat_menulis_bahasa_1",
  "tingkat_menulis_bahasa_2": "getCandidate.tingkat_menulis_bahasa_2",
  "tipe_lulusan_pendidikan_1": "getCandidate.tipe_lulusan_pendidikan_1",
  "tipe_lulusan_pendidikan_2": "getCandidate.tipe_lulusan_pendidikan_2",
  "unit_kerja_kerabat_1": "getCandidate.unit_kerja_kerabat_1",
  "unit_kerja_kerabat_2": "getCandidate.unit_kerja_kerabat_2",
  "unit_kerja_kerabat_3": "getCandidate.unit_kerja_kerabat_3",
  "uraian_jabatan_perusahaan_1": "getCandidate.uraian_jabatan_perusahaan_1",
  "uraian_jabatan_perusahaan_2": "getCandidate.uraian_jabatan_perusahaan_2",
        "rejected_reason": "",
      "rejected_stage_id": "",
      "stage_detail": "",
      "stage_id": "",
      "stage_id_text": "",
      "updated_at": "",
      "updated_by": "",
  "kode_registrasi": "generateRegistrationNumber",
  "user_data_id_text": "getCandidate.id_data_user",
  "user_id_text": "req.candidate.user_id"
}
