var fileName = fileNameClear.split(".csv")[0].trim() + ".csv";
var sheetName = "Sheet 1";
var delimiter = ";";

var datas = [];

if (getData.length != 0) {
  for (i in getData) {
    var data = {
      bank_branch_name: getData[i].bank_branch_name,
      bank_account_number: getData[i].bank_account_number,
      bank_holder_name: getData[i].bank_holder_name,
      bank_name: getData[i].bank_name,
      company_id: getData[i].company_id,
      cost_center: getData[i].cost_center,
      country: getData[i].country,
      created_at: getData[i].created_at,
      created_by: getData[i].created_by,
      date_of_birth: getData[i].date_of_birth,
      directorate: getData[i].directorate,
      ds_email: getData[i].ds_email,
      ds_name: getData[i].ds_name,
      ds_nip: getData[i].ds_nip,
      ds_position_name: getData[i].ds_position_name,
      employee_category: getData[i].employee_category,
      employee_email: getData[i].employee_email,
      employee_name: getData[i].employee_name,
      employee_status: getData[i].employee_status,
      gender: getData[i].gender,
      grade: getData[i].grade,
      id: getData[i].id,
      id_log_response_yoda: getData[i].id_log_response_yoda,
      ktp: getData[i].ktp,
      location: getData[i].location,
      marital_status: getData[i].marital_status,
      nama_file: getData[i].nama_file,
      nip: getData[i].nip,
      npwp: getData[i].npwp,
      org_level: getData[i].org_level,
      position_code: getData[i].position_code,
      position_name: getData[i].position_name,
      postal_code: getData[i].postal_code,
      provinsi: getData[i].provinsi,
      status: getData[i].status,
      sub_directorate: getData[i].sub_directorate,
      tipe_response: getData[i].tipe_response,
      town_of_birth: getData[i].town_of_birth,
      town_or_city: getData[i].town_or_city,
      termination_date: null,
    };
    datas.push(data);
  }
}

// Rubah Nama Header Disini
var headerMap = {
  bank_branch_name: "BANK BRANCH NAME",
  bank_holder_name: "BANK HOLDER NAME",
  bank_account_number: "BANK ACCOUNT NUMBER",
  bank_name: "BANK NAME",
  cost_center: "COST CENTER",
  country: "COUNTRY",
  date_of_birth: "DATE OF BIRTH",
  directorate: "DIRECTORATE",
  ds_email: "DS EMAIL",
  ds_name: "DS NAME",
  ds_nip: "DS NIP",
  ds_position_name: "DS POSITION NAME",
  employee_category: "EMPLOYEE CATEGORY",
  employee_email: "EMAIL ADDRESS",
  employee_name: "EMPLOYEE NAME",
  employee_status: "EMPLOYEE STATUS",
  gender: "GENDER",
  grade: "GRADE",
  ktp: "KTP",
  location: "LOCATION",
  marital_status: "MARITAL STATUS",
  nip: "NIP",
  npwp: "NPWP",
  org_level: "ORG LEVEL",
  position_code: "POSITION CODE",
  position_name: "POSITION NAME",
  postal_code: "POSTAL CODE",
  provinsi: "PROVINSI",
  status: "STATUS",
  sub_directorate: "SUB DIRECTORACE",
  town_of_birth: "TOWN OF BIRTH",
  town_or_city: "TOWN OR CITY",
  termination_date: "TERMINATION DATE",
};

// Rubah Posisi Tiap Kolom Disini
var headerOrder = [
  "employee_email",
  "employee_name",
  "employee_status",
  "termination_date",
  "employee_category",
  "nip",
  "grade",
  "location",
  "directorate",
  "sub_directorate",
  "ktp",
  "npwp",
  "date_of_birth",
  "town_of_birth",
  "gender",
  "marital_status",
  "country",
  "provinsi",
  "town_or_city",
  "postal_code",
  "bank_account_number",
  "bank_holder_name",
  "bank_name",
  "bank_branch_name",
  "position_code",
  "position_name",
  "org_level",
  "cost_center",
  "ds_email",
  "ds_nip",
  "ds_name",
  "ds_position_name",
];

_exportCsv(fileName, datas, headerMap, headerOrder, delimiter);
