var get_employee_core = {
  address: "",
  address_2: "",
  address_3: "",
  address_code: "SM166459/000",
  bank_account_branch: "BRANCH",
  bank_account_holder_name: "Kevin",
  bank_account_number: "872139792123",
  bank_name: {
    id: "CEzpg8w4R",
  },
  city: {
    id: "",
    name: "",
  },
  company_id: 25236,
  company_user_id: 166459,
  country: {
    id: "",
    name: "",
  },
  created_at: 1685427930221,
  created_by: 166448,
  date_of_birth: null,
  email: "yosito.mononimbar@mailnator.com",
  employee_code: "32145",
  employee_id: "",
  employee_status: "INACTIVE",
  employment_type: "",
  end_date: null,
  fax_number: "",
  first_name: "Yosito",
  full_name: "Yosito Kevin",
  gender: "",
  id: "pZlxt8w4R",
  id_key: 1,
  id_master_employee: "pZlxt8w4R",
  identity_number: "",
  is_secretary_mode: false,
  join_date: null,
  last_name: "Kevin",
  marital_status: "",
  pass_nationality: {
    id: "",
    name: "",
  },
  passport_expired_date: null,
  passport_issuing: {
    id: "",
    name: "",
  },
  passport_issuing_date: null,
  passport_number: "",
  password: "12345",
  phone_number: "",
  photo: "",
  place_of_birth: "",
  post_code: 15310,
  salutation: "Mr. (Male, Single)",
  secretary_mode_mapping_team: [],
  state: {
    id: "",
    name: "",
  },
  system_role: "Finance",
  tax_identification_number: "",
  updated_at: 1712044617945,
  updated_by: 166467,
  user_native: false,
  user_organigram_id: 30555,
};

var idUser = get_employee_core.company_user_id;

var updateUserCore = {
  id: idUser,
  email: get_employee_core.email,
  employee_id: "",
  personal_email: "",
  password: "",
  first_name: get_employee_core.first_name,
  last_name: get_employee_core.last_name,
  group_id: 0,
  user_role: 3,
  code: "",
  join_date: null,
  resign_date: null,
  photo_url: "",
  phone_number: get_employee_core.phone_number,
  date_of_birth: get_employee_core.date_of_birth,
  place_of_birth: "",
  bank_account_name: "",
  bank_account_number: "",
  bank_account_owner: "",
  bank_account_branch: "",
  contract_type: "",
  type_of_contract: "",
  active_reason: "",
  non_active_reason: "",
  secretary_mode: false,
  secretary_mode_list_team: [],
  country_id: 0,
  employee_status: 0, // Kalau aktif value nya 1
  other_name: null,
  gender: null,
  nationality_type: "Warga Negara Indonesia (WNI)",
  identity_type: "",
  passport_expired_date: "",
  identity_no: null,
  fax_number: 0,
  religion: null,
  marital_status: null,
  postal_code: null,
  about: "",
  title: "",
  tax_identification_number: 0,
  bpjs_ketenagakerjaan: "",
  bpjs_kesehatan: "",
  ptkp: "",
  max_disbursed_count: 0,
  province_id: "",
  city_id: "",
  office_country_id: "",
  office_province_id: "",
  office_city_id: "",
  contract_start_date: null,
  contract_end_date: null,
  location_id: "",
  address: "",
  office_address: "",
  address_2: "",
  address_3: "",
  post_code: "",
  iban: "",
  managers: [],
  salutation: "",
  passport_no: "",
  passport_issuing: "",
  passport_issuing_date: "",
  passport_nationality: "",
  employment_type_id: 0,
  employment_subtype_id: 0,
  roles: ["claimer"],
};

console.log(updateUserCore);
