var req = {
  body: {
    additional_fields: [
      {
        id: 12234035,
        name: "no__hp",
        value: null,
        value_name: null,
      },
      {
        id: 13473277,
        name: "location",
        value: "3800171",
        value_name: "East Jakarta",
      },
      {
        id: 13473278,
        name: "destination",
        value: "3800174",
        value_name: "Lexus Pluit",
      },
      {
        id: 13567999,
        name: "email_dealer",
        value: null,
        value_name: null,
      },
      {
        id: 13562284,
        name: "customer_public_id",
        value: "22-CP-0000134",
        value_name: "22-CP-0000134",
      },
      {
        id: 14171324,
        name: "nama",
        value: "Ade Sanjaya",
        value_name: "Ade Sanjaya",
      },
      {
        id: 13806663,
        name: "temporary_customer_id",
        value: null,
        value_name: null,
      },
      {
        id: 13560722,
        name: "vin",
        value: "VIN0192817394857",
        value_name: "VIN0192817394857",
      },
      {
        id: 14181086,
        name: "plate_no",
        value: "B-1988-RLB",
        value_name: "B-1988-RLB",
      },
      {
        id: 14171238,
        name: "service_date",
        value: null,
        value_name: null,
      },
      {
        id: 14168845,
        name: "ldms_wo_id",
        value: null,
        value_name: null,
      },
      {
        id: 13561419,
        name: "variant",
        value: "3837304",
        value_name: "General",
      },
      {
        id: 14181431,
        name: "description",
        value: "",
        value_name: "",
      },
      {
        id: 13562529,
        name: "ldms_customer_id",
        value: null,
        value_name: null,
      },
      {
        id: 14171237,
        name: "service_type",
        value: "4070778",
        value_name: "Regular Check (RC)",
      },
      {
        id: 13560634,
        name: "phone_number",
        value: null,
        value_name: null,
      },
      {
        id: 13560721,
        name: "domisili",
        value: null,
        value_name: null,
      },
      {
        id: 13473449,
        name: "complaint_type__sales",
        value: null,
        value_name: null,
      },
      {
        id: 13560808,
        name: "subject_type",
        value: "3837161",
        value_name: "After Sales",
      },
      {
        id: 13561075,
        name: "category",
        value: "3837207",
        value_name: "Request",
      },
      {
        id: 13561331,
        name: "category_complaint",
        value: "3837271",
        value_name: "Non-Serious Complaint",
      },
      {
        id: 13561332,
        name: "sub_category",
        value: "3837278",
        value_name: "Request",
      },
      {
        id: 13561422,
        name: "customer_source",
        value: "3837310",
        value_name: "Event",
      },
      {
        id: 13562019,
        name: "channel",
        value: "3837484",
        value_name: "Walk In",
      },
      {
        id: 13562105,
        name: "urgency_level",
        value: "3837553",
        value_name: "Normal",
      },
      {
        id: 13562193,
        name: "interaction_type",
        value: "-",
        value_name: "-",
      },
      {
        id: 13562194,
        name: "interface_ticket_qontak",
        value: "3837580",
        value_name: "True",
      },
      {
        id: 13562211,
        name: "remarks",
        value: null,
        value_name: null,
      },
      {
        id: 14172261,
        name: "closed_remarks",
        value: "-",
        value_name: "-",
      },
      {
        id: 13562283,
        name: "status_concierge",
        value: null,
        value_name: null,
      },
      {
        id: 13562300,
        name: "status_dealer_service",
        value: null,
        value_name: null,
      },
      {
        id: 13562374,
        name: "status_lmcs",
        value: null,
        value_name: null,
      },
      {
        id: 13562375,
        name: "schedule",
        value: null,
        value_name: null,
      },
      {
        id: 13562462,
        name: "concierge_key",
        value: null,
        value_name: null,
      },
      {
        id: 13562463,
        name: "message",
        value: null,
        value_name: null,
      },
      {
        id: 13562464,
        name: "l_reach_location",
        value: null,
        value_name: null,
      },
      {
        id: 13562479,
        name: "coordinate",
        value: null,
        value_name: null,
      },
      {
        id: 13562723,
        name: "url_l_reach",
        value: null,
        value_name: null,
      },
      {
        id: 13562724,
        name: "dealer_booking_service_id",
        value: null,
        value_name: null,
      },
      {
        id: 13562725,
        name: "lmcs_id",
        value: null,
        value_name: null,
      },
      {
        id: 13616060,
        name: "dealer_req_key",
        value: null,
        value_name: null,
      },
      {
        id: 13616061,
        name: "dealer_name",
        value: null,
        value_name: null,
      },
      {
        id: 13616062,
        name: "food_beverages",
        value: null,
        value_name: null,
      },
      {
        id: 13669344,
        name: "service_type_l_reach",
        value: null,
        value_name: null,
      },
      {
        id: 14184596,
        name: "mtoyota_phone_number",
        value: null,
        value_name: null,
      },
      {
        id: 14184597,
        name: "cc_phone_number",
        value: null,
        value_name: null,
      },
      {
        id: 14184598,
        name: "cc_subscription_id",
        value: null,
        value_name: null,
      },
      {
        id: 14428309,
        name: "dealer_code",
        value: null,
        value_name: null,
      },
      {
        id: 14436972,
        name: "status_ticket_qontak",
        value: null,
        value_name: null,
      },
      {
        id: 14439961,
        name: "ldms_vehicle_id",
        value: null,
        value_name: null,
      },
      {
        id: 14451134,
        name: "is_from_lexus_reach",
        value: null,
        value_name: null,
      },
      {
        id: 14451135,
        name: "is_telematics_emergency",
        value: null,
        value_name: null,
      },
      {
        id: 14451232,
        name: "is_telematics_renewal",
        value: null,
        value_name: null,
      },
      {
        id: 14451329,
        name: "is_telematics_disconnected",
        value: null,
        value_name: null,
      },
    ],
    channel_integration_room_id: null,
    closed_date: null,
    created_at: "2024-08-30T14:27:59.602+07:00",
    creator_id: 185776,
    creator_name: "Rizky Pambudi -",
    crm_company_id: null,
    crm_company_name: null,
    crm_lead_ids: [],
    crm_lead_name: [],
    crm_lost_reason_id: null,
    crm_lost_reason_name: null,
    crm_pipeline_id: 150181,
    crm_pipeline_name: "Accident",
    crm_priority_id: null,
    crm_priority_name: null,
    crm_source_id: null,
    crm_source_name: null,
    crm_stage_id: 904418,
    crm_stage_name: "On Progress",
    currency: "IDR",
    expired_date: null,
    external_company_id: 836993,
    id: 55263135,
    name: "22-CP-0000134 - Ade Sanjaya",
    product_association_ids: [],
    product_association_name: [],
    product_association_price: [],
    product_association_quantity: [],
    product_association_total_price: [],
    size: null,
    slug: "54227d60-b4d6-45d8-9383-891be5b9ee3a",
    start_date: "2024-08-30T14:27:59.000+07:00",
    updated_at: "2024-08-30T14:42:03.229+07:00",
  },
};
