var req = {
  body: {
    company_id: 27414,
    data: {
      created_date: "2025-10-07 16:55:43",
      form_data_id: "aCGBEGOPEEMlthr2",
      id: 2045,
      metadata:
        '{"_id":"68e4e398813bb71b981d8d21","allowance_take_date":1759770000000,"attachments":[],"cancel_status":"NO","company_id":27414,"created_at":1759830935896,"created_by":187860,"day":7,"deduct_holiday":false,"deduct_joint_holiday":true,"delegasi":"","employee_id_text":"EwFwpuEhZxmD","end_date":1763917200000,"estimated_due_date":null,"flow_status":"draft","id":"9LK5exdFuqk","id_pengajuan_employee_cuti":"9LK5exdFuqk","is_allowance":true,"is_allowance_take":"Sudah Diambil","kuota_cuti":6,"leave_expiry_date":1782752400000,"master_leave_quota":15,"month":10,"nama_karyawan":"Tandi Mazmur August","nama_requestor":"Tandi Mazmur August","no_handphone":"","npk_karyawan":154991388,"npk_requestor":154991388,"once_request":false,"permission_id":{"id":"RHbZM0yercN3","name":"Cuti Tahunan 2025"},"reason":"","requested_by_npk":"154991388","start_date":1763658000000,"submission_exp_ts":1790787600000,"total_date":2,"type_aps":"WEB","type_id":{"id":"oP8TJmD8G7Moleaq","name":"Cuti"},"unit_kerja_karyawan":{"id":"CmoCmjOSgrCo","name":"Sub Bidang Pelayanan Kantor Wilayah DKI Jakarta"},"unit_kerja_requestor":{"id":"CmoCmjOSgrCo","name":"Sub Bidang Pelayanan Kantor Wilayah DKI Jakarta"},"updated_at":1759830941820,"updated_by":187860,"wilayah_karyawan":{"id":"lNcoQ1xiYG9E","name":"Grup Konsolidasi Kantor Wilayah DKI Jakarta"},"wilayah_requestor":{"id":"lNcoQ1xiYG9E","name":"Grup Konsolidasi Kantor Wilayah DKI Jakarta"},"workflow_id":"pengajuan_cuti","year":2025}',
      need_revision: 0,
      need_revision_name: "UNKNOWN",
      package: 100,
      process: [
        {
          created_date: "2025-10-07 16:55:43",
          flow_id: 0,
          flow_member_id: 0,
          flow_name: "BY REPORTING LINE",
          id: 3904,
          organigram_id: 783,
          rule_id: 0,
          user: {
            bank_account_branch: "",
            bank_account_branch_code: "",
            bank_account_name: "",
            bank_account_number: "",
            bank_account_owner: "",
            company_id: 27414,
            contract_time_remaining: "not available",
            contract_type: "",
            created_date: "2025-09-27 01:47:40",
            effective_end_date: null,
            effective_start_date: null,
            email: "deny.yusyulian@bpjsketenagakerjaan.go.id",
            employee_code: "201289972",
            employee_id: "",
            employee_status: 1,
            employment_subtype_id: 0,
            employment_subtype_name: null,
            employment_type_id: 0,
            employment_type_name: "",
            group_id: 0,
            id: 187858,
            is_active: true,
            join_date: "",
            length_of_working: "",
            location: "",
            location_id: null,
            non_active_reason: "",
            office_address: null,
            position: "",
            profile: {
              about: "",
              address: "",
              address_2: "",
              address_3: "",
              address_type: 0,
              age: 0,
              change_password_date: null,
              city: "",
              city_id: 0,
              country: "",
              country_id: 0,
              created_date: "2025-09-27 01:47:40",
              date_of_birth: "",
              dialing_code: "",
              email: "deny.yusyulian@bpjsketenagakerjaan.go.id",
              employee_id: "",
              expired_date: "",
              fax_number: "",
              first_name: "Deny Yusyulian",
              gender: "",
              iban: "",
              id: 215189,
              id_expired_date: "",
              id_number: "",
              id_type: 0,
              identity_number: "",
              identity_type: "",
              last_name: "",
              latitude: 0,
              longitude: 0,
              marital_status: "",
              mobile_phone: "",
              nationality_type: "Warga Negara Indonesia (WNI)",
              other_name: "",
              passport_expirity_date: "",
              passport_issuing: "",
              passport_issuing_alpha2: "",
              passport_issuing_alpha3: "",
              passport_issuing_date: "",
              passport_issuing_id: 0,
              passport_nationality: "",
              passport_nationality_alpha2: "",
              passport_nationality_alpha3: "",
              passport_nationality_id: 0,
              passport_number: "",
              personal_email: "",
              phone: "",
              phone_country_id: 0,
              phone_number: "",
              photo_url: "",
              place_of_birth: "",
              post_code: "",
              postal_code: "",
              province: "",
              province_id: 0,
              religion: "",
              role_names: ["claimer"],
              salutation: "",
              updated_date: "2025-09-27 01:47:40",
              user_company_id: 187858,
              user_id: 215929,
              user_role: 3,
              user_role_name: "user",
            },
            reasons: "",
            resign_date: "",
            status: null,
            type_of_contract: "",
            updated_date: "2025-09-27 01:47:40",
            user_role: 3,
            user_role_name: "user",
          },
        },
      ],
      reference_id: 147081261,
      rule_id: 0,
      status: 2,
      status_name: "SENT",
      target: 7,
      target_name: "TARGET_WITH_ADVANCED_ORGANIGRAM",
      updated_date: "2025-10-07 16:55:43",
    },
    event_name: "flow_request_approve",
    triggered_by: 187861,
  },
};


var form_data_id = req.body.data.form_data_id;
var approveData = JSON.parse(req.body.data.metadata);
var workflow_id = approveData.workflow_id;
var next_approvers = [];

req.body.data.process.forEach(function (process) {
    next_approvers.push(process.user.id);
});


var payload = {
    id_data: approveData.id,
    form_data_id: form_data_id,
    workflow_id: workflow_id,
    next_approvers: next_approvers,
};

// console.log(approveData);
// console.log(workflow_id);
console.log(payload);