var getApplicantDetail = {
  agama: "Islam",
  akreditasi_pendidikan_1: "",
  akreditasi_pendidikan_2: "",
  alamat_domisili: "Jl. Melati No.88, Cibubur",
  alamat_institusi_pendidikan_1: "",
  alamat_institusi_pendidikan_2: "",
  alamat_ktp: "Jl. Cendrawasih No.45, Antapani",
  alamat_lembaga_pelatihan_1: "",
  alamat_lembaga_pelatihan_2: "",
  applied_job_position: "MANGER - 2",
  bahasa_1: "",
  bahasa_2: "",
  berat_badan: 70,
  bidang_organisasi_1: "",
  bidang_organisasi_2: "",
  bidang_pelatihan_1: "",
  bidang_pelatihan_2: "",
  bidang_perusahaan_pengalaman_1: "",
  bidang_perusahaan_pengalaman_2: "",
  bulan_akhir_organisasi_1: "",
  bulan_akhir_organisasi_2: "",
  bulan_akhir_perusahaan_1: "",
  bulan_akhir_perusahaan_2: "",
  bulan_awal_organisasi_1: "",
  bulan_awal_organisasi_2: "",
  bulan_awal_perusahaan_1: "",
  bulan_awal_perusahaan_2: "",
  company_id: 27414,
  created_at: 0,
  created_by: 178566,
  email: "",
  fakultas_pendidikan_1: "",
  fakultas_pendidikan_2: "",
  file_cv: "",
  file_ijazah_pendidikan_terakhir: "",
  file_sertifikasi_1: "",
  file_sertifikasi_2: "",
  first_name: "",
  flow_status: "",
  gaji_terakhir_perusahaan_1: 0,
  gaji_terakhir_perusahaan_2: 0,
  handphone_1: "",
  handphone_2: "",
  id: "Dc6UuO9pSbYVP1Yt",
  instansi_ayah: "",
  instansi_ibu: "",
  instansi_saudara_1: "",
  instansi_saudara_2: "",
  instansi_saudara_3: "",
  institusi_pendidikan_1: "",
  institusi_pendidikan_2: "",
  ipk_pendidikan_1: "",
  ipk_pendidikan_2: "",
  jabatan_akhir_perusahaan_1: "",
  jabatan_akhir_perusahaan_2: "",
  jabatan_awal_perusahaan_1: "",
  jabatan_awal_perusahaan_2: "",
  jabatan_organisasi_1: "",
  jabatan_organisasi_2: "",
  jenis_kelamin: "",
  jenis_kelamin_saudara_1: "",
  jenis_kelamin_saudara_2: "",
  jenis_kelamin_saudara_3: "",
  jenis_perusahaan_pengalaman_1: "",
  jenis_perusahaan_pengalaman_2: "",
  jenjang_pendidikan_1: "",
  jenjang_pendidikan_2: "",
  jumlah_kantor_cabang_perusahaan_1: 0,
  jumlah_kantor_cabang_perusahaan_2: 0,
  jumlah_karyawan_perusahaan_1: 0,
  jumlah_karyawan_perusahaan_2: 0,
  jurusan_pendidikan_1: "",
  jurusan_pendidikan_2: "",
  kabupaten_domisili: "",
  kabupaten_institusi_pendidikan_1: "",
  kabupaten_institusi_pendidikan_2: "",
  kabupaten_ktp: "",
  kabupaten_lembaga_pelatihan_1: "",
  kabupaten_lembaga_pelatihan_2: "",
  kode_pendaftaran: "Dc6UuO9pSbYVP1Yt",
  kodepos_domisili: "",
  kodepos_institusi_pendidikan_1: "",
  kodepos_institusi_pendidikan_2: "",
  kodepos_ktp: "",
  kodepos_lembaga_pelatihan_1: "",
  kodepos_lembaga_pelatihan_2: "",
  ktp_valid_until: 0,
  last_name: "",
  lembaga_pelatihan_1: "",
  lembaga_pelatihan_2: "",
  nama_ayah: "",
  nama_ibu: "",
  nama_lengkap: "John Doe",
  nama_organisasi_1: "",
  nama_organisasi_2: "",
  nama_pelatihan_1: "",
  nama_pelatihan_2: "",
  nama_saudara_1: "",
  nama_saudara_2: "",
  nama_saudara_3: "",
  nik: "",
  no_ijazah_pendidikan_1: "",
  no_ijazah_pendidikan_2: "",
  no_kk: "",
  pekerjaan_ayah: "",
  pekerjaan_ibu: "",
  pekerjaan_saudara_1: "",
  pekerjaan_saudara_2: "",
  pekerjaan_saudara_3: "",
  period_id: {
    id: "GkdHmziMiiAqUVav",
    name: "Periode 1",
  },
  period_id_text: "GkdHmziMiiAqUVav",
  pernah_toefl_ielts: "",
  perusahaan_pengalaman_1: "",
  perusahaan_pengalaman_2: "",
  photo_full_body: "",
  photo_half_body: "",
  photo_profile: "",
  pipeline_id: {
    id: "",
    name: "",
  },
  provinsi_domisili: "",
  provinsi_institusi_pendidikan_1: "",
  provinsi_institusi_pendidikan_2: "",
  provinsi_ktp: "",
  provinsi_lembaga_pelatihan_1: "",
  provinsi_lembaga_pelatihan_2: "",
  punya_kerabat_bpjs: "",
  rejected_reason: "",
  rejected_stage_id: {
    id: "",
    name: "",
  },
  stage_detail: null,
  stage_id: {
    id: "",
    name: "",
  },
  status_kawin: "",
  status_lulus_pendidikan_1: "",
  status_lulus_pendidikan_2: "",
  tahun_akhir_organisasi_1: 0,
  tahun_akhir_organisasi_2: 0,
  tahun_akhir_perusahaan_1: 0,
  tahun_akhir_perusahaan_2: 0,
  tahun_awal_organisasi_1: 0,
  tahun_awal_organisasi_2: 0,
  tahun_awal_perusahaan_1: 0,
  tahun_awal_perusahaan_2: 0,
  tahun_mulai_pendidikan_1: 0,
  tahun_mulai_pendidikan_2: 0,
  tahun_pelatihan_1: "",
  tahun_pelatihan_2: "",
  tahun_selesai_pendidikan_1: 0,
  tahun_selesai_pendidikan_2: 0,
  tanggal_lahir: 0,
  tanggal_lahir_ayah: 0,
  tanggal_lahir_ibu: 0,
  tanggal_lahir_saudara_1: 0,
  tanggal_lahir_saudara_2: 0,
  tanggal_lahir_saudara_3: 0,
  telepon: "",
  tempat_lahir: "",
  tinggi_badan: 0,
  tingkat_lisan_bahasa_1: "",
  tingkat_lisan_bahasa_2: "",
  tingkat_membaca_bahasa_1: "",
  tingkat_membaca_bahasa_2: "",
  tingkat_mendengar_bahasa_1: "",
  tingkat_mendengar_bahasa_2: "",
  tingkat_menulis_bahasa_1: "",
  tingkat_menulis_bahasa_2: "",
  tipe_lulusan_pendidikan_1: "",
  tipe_lulusan_pendidikan_2: "",
  updated_at: 1745315212481,
  updated_by: 178566,
  uraian_jabatan_perusahaan_1: "",
  uraian_jabatan_perusahaan_2: "",
  user_data_id_text: "",
  user_id_text: "",
};

function getSafeValue(value) {
  return value !== undefined && value !== null && String(value).trim() !== "" ? value : "--";
}

function formatTanggal(timestampInput) {
  if (timestampInput === null || timestampInput === undefined) {
    return "--";
  }

  var date = new Date(timestampInput);

  if (isNaN(date.getTime())) {
    return "--";
  }

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  var formattedDay = ("0" + day).slice(-2);
  var formattedMonth = ("0" + month).slice(-2);

  return formattedDay + "-" + formattedMonth + "-" + year;
}

var defaultImageProfile =
  "http://officeless-bpjs-prod-public.oss-ap-southeast-5.aliyuncs.com/27414/68086d2b81aec-Screenshot_395.png";

var dataApplicant = {
  // Informasi Pribadi
  "var_no_ktp": getSafeValue(getApplicantDetail.provinsi_ktp),
  "var_nama_lengkap": getSafeValue(getApplicantDetail.nama_lengkap),
  "var_tempat_lahir": getSafeValue(getApplicantDetail.tempat_lahir),
  "var_tanggal_lahir": formatTanggal(getApplicantDetail.tanggal_lahir),
  "var_jenis_kelamin": getSafeValue(getApplicantDetail.jenis_kelamin),
  "var_foto_profile": getApplicantDetail.photo_profile && getApplicantDetail.photo_profile.trim() !== "" ? getApplicantDetail.photo_profile : defaultImageProfile,
  "var_agama": getSafeValue(getApplicantDetail.agama),
  "var_status_perkawinan": getSafeValue(getApplicantDetail.status_kawin),
  "var_tinggi_badan": getSafeValue(getApplicantDetail.tinggi_badan),
  "var_berat_badan": getSafeValue(getApplicantDetail.berat_badan),
  
  // Alamat
  "var_alamat_ktp": getSafeValue(getApplicantDetail.alamat_ktp),
  "var_alamat_domisili": getSafeValue(getApplicantDetail.alamat_domisili),
  
  // Kontak
  "var_handphone_1": getSafeValue(getApplicantDetail.handphone_1),
  "var_handphone_2": getSafeValue(getApplicantDetail.handphone_2),
  "var_email": getSafeValue(getApplicantDetail.email),
  "var_telepon": getSafeValue(getApplicantDetail.telepon),
  
  // Pendidikan
  "var_jenjang": getSafeValue(getApplicantDetail.jenjang_pendidikan_1),
  "var_ipk": getSafeValue(getApplicantDetail.ipk_pendidikan_1),
  "var_nomor_seri_ijazah": getSafeValue(getApplicantDetail.no_ijazah_pendidikan_1),
  "var_akreditasi": getSafeValue(getApplicantDetail.akreditasi_pendidikan_1),
  "var_nama_institusi_pendidikan": getSafeValue(getApplicantDetail.institusi_pendidikan_1),
  "var_jurusan_program_studi": getSafeValue(getApplicantDetail.jurusan_pendidikan_1),
  "var_alamat_pendidikan": getSafeValue(getApplicantDetail.alamat_institusi_pendidikan_1),
  "var_tahun_pendidikan": getSafeValue(getApplicantDetail.tahun_mulai_pendidikan_1),
  "var_status_lulus_pendidikan": getSafeValue(getApplicantDetail.status_lulus_pendidikan_1),
  "var_telepon_institusi_pendidikan_1": getSafeValue(getApplicantDetail.telepon), // belum clear
};

console.log(dataApplicant);

