var data = {
    amount: 0,
    branch: {},
    company_code: {},
    converted_amount: 0,
    currency_code: {},
    customer_account_number: "",
    description_cc: "",
    drcr: "",
    exchange_rate: 0,
    fk_id_adi_transaction: "",
    gl_account: {},
    gl_sub_account: {},
    line_description: "",
    line_number: 0,
    optional_2: {},
    optional_3: {},
    product: {},
    rc_code: {},
    reference_number: "",
};