var idUser = get_employee_core.company_user_id;

var updateUserCore = {
  "id": idUser,
  "email": get_employee_core.email,
  "employee_id": "",
  "personal_email": "",
  "password": "",
  "first_name": get_employee_core.first_name,
  "last_name": get_employee_core.last_name,
  "group_id": 0,
  "user_role": 3,
  "code": "",
  "join_date": null,
  "resign_date": null,
  "photo_url": "",
  "phone_number": "",
  "date_of_birth": "",
  "place_of_birth": "",
  "bank_account_name": "",
  "bank_account_number": "",
  "bank_account_owner": "",
  "bank_account_branch": "",
  "contract_type": "",
  "type_of_contract": "",
  "active_reason": "",
  "non_active_reason": "",
  "secretary_mode": false,
  "secretary_mode_list_team": [],
  "country_id": 0,
  "employee_status": 0,  // Kalau active jadi 1
  "other_name": null,
  "gender": null,
  "nationality_type": "Warga Negara Indonesia (WNI)",
  "identity_type": "",
  "passport_expired_date": "",
  "identity_no": null,
  "fax_number": 0,
  "religion": null,
  "marital_status": null,
  "postal_code": null,
  "about": "",
  "title": "",
  "tax_identification_number": 0,
  "bpjs_ketenagakerjaan": "",
  "bpjs_kesehatan": "",
  "ptkp": "",
  "max_disbursed_count": 0,
  "province_id": "",
  "city_id": "",
  "office_country_id": "",
  "office_province_id": "",
  "office_city_id": "",
  "contract_start_date": null,
  "contract_end_date": null,
  "location_id": "",
  "address": "",
  "office_address": "",
  "address_2": "",
  "address_3": "",
  "post_code": "",
  "iban": "",
  "managers": [],
  "salutation": "",
  "passport_no": "",
  "passport_issuing": "",
  "passport_issuing_date": "",
  "passport_nationality": "",
  "employment_type_id": 0,
  "employment_subtype_id": 0,
  "roles": ["claimer"]
}


_log(updateUserCore);