var listColumn = {
  "_id": 0,
  "BRANCH ID": "$branch_id",
  "BRANCH TYPE": "$branch_type",
  "AWB DATE": "$awb_date",
  "AWB NUMBER": "$awb_number",
  "CUSTOMER ID": "$customer_id",
  "CUSTOMER NAME": "$customer_name",
  "LOCAL PARENT ID": "$local_parent_id",
  "LOCAL PARENT ID NAME": "$local_parent_name",
  "NATIONAL PARENT ID": "$national_parent_id",
  "NATIONAL PARENT ID NAME": "$national_parent_name",
  "BRANCH NAME": "$branch_name",
  "SITE ID": "$site_id",
  "SITE ID NAME": "$site_name",
  "CUSTOMER TYPE": "$customer_type",
  "CUSTOMER TYPE NAME": "$customer_type_name",
  "INDUSTRY TYPE CODE": "$industry_type_code",
  "INDUSTRY TYPE NAME": "$industry_type_name",
  "CONTRACT NUMBER": "$contract_number",
  "CONTRACT VALIDITY PERIOD - FROM DATE": "$contract_validity_period_from_date",
  "CONTRACT VALIDITY PERIOD - TO DATE": "$contract_validity_period_to_date",
  "(CHECK BOX) - BILLED BY SITE": "$check_box_billed_by_site",
  "INVOICING METHOD": "$flagging_multi_or_local_branch",
  "NA PRINCIPAL": "$na_principal",
  "IS CASHLESS?": "$is_cashless",
  "TERM OF PAYMENT": "$term_of_payment",
  "CURRENCY": "$currency",
  "GENERATE MASS STANDARD INVOICE": "$generate_mass_standard_invoice",
  "CREATION DATE AND TIME": "$creation_date_and_time",
  "CCRF LAST UPDATE DATE AND TIME (ORION/SALES FORCE & BMS)": "$ccrf_last_update_date_and_time_the_core",
  "ORIGIN SYS CODE (ORION)": "$origin_sys_code",
  "ORIGIN CITY NAME (ORION)": "$origin_city_name",
  "ORIGIN ZIP CODE (ORION)": "$origin_zip_code_orion",
  "DESTINATION SYS CODE (ORION)": "$destination_sys_code",
  "DESTINATION CITY NAME (ORION)": "$destination_city_name",
  "DESTINATION ZIP CODE (ORION)": "$destination_zip_code_orion",
  "ROUTE CODE": "$route_code",
  "ORIGIN BRANCH ID": "$origin_branch_id",
  "ORIGIN ID": "$origin_id",
  "ORIGIN ID NAME": "$origin_name",
  "ORIGIN URBAN VILLAGE NAME": "$origin_urban_village_name",
  "ORIGIN DISTRICT NAME": "$origin_district_name",
  "ORIGIN ZONE": "$origin_zone",
  "ORIGIN CITY NAME": "$origin_city_name",
  "ORIGIN PROVINCE NAME": "$origin_province_name",
  "ORIGIN ZIP CODE (BMS)": "$origin_zip_code_bms",
  "DESTINATION BRANCH ID": "$destination_branch_id",
  "DESTINATION ID": "$destination_id",
  "DESTINATION ID NAME": "$destination_name",
  "DESTINATION URBAN VILLAGE NAME": "$destination_urban_village_name",
  "DESTINATION DISTRICT NAME": "$destination_district_name",
  "DESTINATION ZONE": "$destination_zone",
  "DESTINATION CITY NAME": "$destination_city_name",
  "DESTINATION PROVINCE NAME": "$destination_province_name",
  "DESTINATION ZIP CODE (BMS)": "$destination_zip_code_bms",
  "ORIGIN - DESTINATION ID": "$origin_destination_id",
  "ORIGIN RATE CARD ID": "$origin_rate_card_id",
  "ORIGIN RATE CARD ID NAME": "$origin_rate_card_id_name",
  "DESTINATION RATE CARD ID": "$destination_rate_card_id",
  "DESTINATION RATE CARD ID NAME": "$destination_rate_card_id_name",
  "QUANTITY": "$quantity",
  "WEIGHT (KG)": "$weight_kg",
  "WEIGHT (GRAM)": "$weight_gram",
  "HEIGHT": "$height",
  "WIDTH": "$width",
  "LENGTH": "$length",
  "VOLUMETRIC WEIGHT (H X W X L)": "$volumetric_weight_h_x_w_x_l",
  "SHIPPER NAME": "$shipper_name",
  "SHIPPER ADDRESS - STREET": "$shipper_address_street",
  "SHIPPER ADDRESS - DISTRICT": "$shipper_address_district",
  "SHIPPER ADDRESS - CITY": "$shipper_address_city",
  "SHIPPER ADDRESS - PROVINCE": "$shipper_address_province",
  "SHIPPER ADDRESS - ZIP CODE": "$shipper_address_zip_code",
  "SHIPPER PIC NAME": "$shipper_pic_name",
  "CONSIGNEE NAME": "$consignee_name",
  "CONSIGNEE ADDRESS - STREET": "$consignee_address_street",
  "CONSIGNEE ADDRESS - DISTRICT": "$consignee_address_district",
  "CONSIGNEE ADDRESS - CITY": "$consignee_address_city",
  "CONSIGNEE ADDRESS - PROVINCE": "$consignee_address_province",
  "CONSIGNEE ADDRESS - ZIP CODE": "$consignee_address_zip_code",
  "CONSIGNEE PIC NAME": "$consignee_pic_name",
  "GOODS TYPE": "$goods_type",
  "GOODS DESCRIPTION": "$goods_description",
  "GOODS VALUE": "$goods_value",
  "ORIGINAL AMOUNT": "$original_amount_number",
  "ORIGINAL AMOUNT PER KG": "$original_amount_per_kg",
  "PRICING DETAIL COMBINATION ID": "$pricing_combination_id",
  "PRICING DETAIL COMBINATION NAME": "$pricing_model_name",
  "DISCOUNT AMOUNT (AWB)": "$discount_amount_awb_number",
  "ADJUSTED AMOUNT": "$adjusted_amount_number",
  "PACKING FLAG": "$packing_flag",
  "PACKING": "$packing_number",
  "SURCHARGE": "$surcharge_number",
  "OTHER CHARGES": "$other_charges_number",
  "TOTAL PACKING & CHARGES": "$total_packing_charges_number",
  "TOTAL AMOUNT AFTER DISCOUNT & CHARGES (DPP)": "$total_amount_after_discount_charges_dpp",
  "VAT - FREIGHT": "$vat_freight",
  "INSURANCE FLAG": "$insurance_flag",
  "INSURANCE ID": "$insurance_id",
  "INSURANCE NUMBER": "$insurance_number",
  "ORIGINAL INSURANCE ADMIN": "$original_insurance_admin",
  "ORIGINAL INSURANCE PREMI": "$original_insurance_premi",
  "INSURANCE CHARGE (IDR)": "$insurance_charge",
  "ADJUSTED INSURANCE PREMI": "$adjusted_insurance_premi_number",
  "ADJUSTED INSURANCE ADMIN": "$adjusted_insurance_admin_number",
  "TOTAL ADJUSTED INSURANCE AMOUNT (CHARGED TO CUSTOMER)": "$total_adjusted_insurance_amount",
  "PAID AMOUNT": "$paid_amount",
  "PAYMENT TYPE": "$payment_type",
  "COD FLAG": "$cod_flag",
  "% COD FEE": "$persentase_cod_fee",
  "COD FEE AMOUNT": "$cod_fee_amount",
  "COD FEE ZONE": "$cod_fee_zone",
  "COD AMOUNT - PAID TO CUSTOMER": "$cod_amount_paid_to_customer",
  "DIFFERENCE COD AMOUNT - PAID TO CUSTOMER": "$difference_cod_amount_paid_to_customer",
  "NOTA TAGIHAN COD - PAID TO CUSTOMER": "$nota_tagihan_cod_paid_to_customer",
  "TANGGAL PEMBAYARAN COD": "$tanggal_pembayaran_cod",
  "PERIODE TRANSAKSI COD": "$periode_transaksi_cod",
  "TRACKING NUMBER ID": "$tracking_number_id",
  "AWB RETURN NUMBER": "$awb_return_number",
  "CONNOTE REMARK": "$connote_remark",
  "HANDLING CONNOTE TYPE": "$handling_connote_type",
  "E-CONNOTE FLAG": "$econnote_flag",
  "CONNOTE MUST BE ATTACHED FLAG": "$connote_must_be_attached_flag",
  "DELIVERY ORDER FLAG": "$delivery_order_flag",
  "USER - APPROVAL CONNOTE DATA ENTRY": "$user_approval_connote_data_entry",
  "CONNOTE CREATED DATE & TIME": "$connote_created_date_time",
  "APPROVAL CONNOTE DATA ENTRY DATE & TIME": "$approval_connote_data_entry_date_time",
  "CONNOTE CANCEL": "$connote_cancel",
  "CONNOTE CANCEL REASON": "$connote_cancel_reason",
  "CONNOTE HOLD": "$connote_hold",
  "CONNOTE HOLD REASON": "$connote_hold_reason",
  "PICK UP BY BRANCH": "$pick_up_by_branch",
  "PICK UP REQUEST NUMBER": "$pick_up_request_number",
  "PICK UP ORDER ID": "$pick_up_order_id",
  "PICK UP REQUEST DATE & TIME": "$pick_up_request_date_time",
  "USER - PICK UP REQUEST CREATED BY": "$user_pick_up_request_created_by",
  "PICK UP REQUEST APPROVED DATE & TIME": "$pick_up_request_approved_date_time",
  "PICK UP REQUEST READY DATE & TIME": "$pick_up_request_ready_date_time",
  "USER - REQUEST PICK UP READY CREATED BY": "$user_request_pick_up_ready_created_by",
  "PICK UP CONFIRMED DATE & TIME": "$pick_up_confirmed_date_time",
  "USER - PICK UP CONFIRMED CREATED BY": "$user_pick_up_confirmed_created_by",
  "RE PICK UP DATE & TIME": "$re_pick_up_date_time",
  "RE PICK UP COURIER ID": "$re_pick_up_courier_id",
  "RE PICK UP COURIER NAME": "$re_pick_up_courier_name",
  "PICK UP REQUEST CANCELLED DATE & TIME": "$pick_up_request_cancelled_date_time",
  "USER - PICK UP REQUEST CANCELLED BY": "$user_pick_up_request_cancelled_by",
  "PICK UP REQUEST CANCELLED REMARK": "$pick_up_request_cancelled_remark",
  "PICK UP DATE & TIME": "$pick_up_date_time",
  "PICK UP COURIER ID": "$pick_up_courier_id",
  "PICK UP COURIER NAME": "$pick_up_courier_name",
  "PICK UP ADDRESS - STREET": "$pick_up_address_street",
  "PICK UP ADDRESS - DISTRICT": "$pick_up_address_district",
  "PICK UP ADDRESS - CITY": "$pick_up_address_city",
  "PICK UP ADDRESS - PROVINCE": "$pick_up_address_province",
  "PICK UP ADDRESS - ZIP CODE": "$pick_up_address_zip_code",
  "PICK UP PIC NAME": "$pick_up_pic_name",
  "PICK UP PIC PHONE": "$pick_up_pic_phone",
  "PICK UP STATUS": "$pick_up_status",
  "PICK UP VEHICLE": "$pick_up_vehicle",
  "PICK UP SPECIAL INSTRUCTION": "$pick_up_special_instruction",
  "PICK UP REQUEST RECEIVED DATE & TIME": "$pick_up_request_received_date_time",
  "USER - PICK UP REQUEST RECEIVED BY": "$user_pick_up_request_received_by",
  "SLA DAYS": "$sla_days",
  "SLA DATE": "$sla_date",
  "RECEIVING & CHECKING CONNOTE DATE & TIME": "$receiving_checking_connote_date_time",
  "RECEIVING & CHECKING CONNOTE NO": "$receiving_checking_connote_no",
  "RECEIVING & CHECKING CONNOTE REMARK": "$receiving_checking_connote_remark",
  "RECEIVER & CHECKER CONNOTE - PIC NAME": "$receiver_checker_connote_pic_name",
  "USER - RECEIVING & CHECKING CONNOTE": "$user_receiving_checking_connote",
  "USER - APPROVAL RECEIVING & CHECKING CONNOTE": "$user_approval_receiving_checking_connote",
  "UPDATED WEIGHT (YES/NO)": "$updated_weight_yes_no",
  "UPDATED WEIGHT (KGS)": "$updated_weight_kgs",
  "UPDATED HEIGHT": "$updated_height",
  "UPDATED WIDTH": "$updated_width",
  "UPDATED LENGTH": "$updated_length",
  "UPDATED VOLUMETRIC WEIGHT (H X W X L)": "$updated_volumetric_weight_h_x_w_x_l",
  "ACTUAL WEIGHT": "$actual_weight",
  "LAST WEIGHT MODIFIED BY": "$last_weight_modified_by",
  "LAST WEIGHT MODIFIED DATE AND TIME": "$last_weight_modified_date_and_time",
  "UPDATED SERVICE TYPE (YES/NO)": "$updated_service_type_yes_no",
  "UPDATED SERVICE TYPE": "$updated_service_type",
  "LAST SERVICE TYPE MODIFIED BY": "$last_service_type_modified_by",
  "LAST SERVICE TYPE MODIFIED DATE AND TIME": "$last_service_type_modified_date_and_time",
  "UPDATED ORIGIN CODE (YES/NO)": "$updated_origin_code_yes_no",
  "UPDATED ORIGIN CODE": "$updated_origin_code",
  "LAST ORIGIN CODE MODIFIED BY": "$last_origin_code_modified_by",
  "LAST ORIGIN CODE MODIFIED DATE AND TIME": "$last_origin_code_modified_date_and_time",
  "UPDATED DESTINATION CODE (YES/NO)": "$updated_destination_code_yes_no",
  "UPDATED DESTINATION CODE": "$updated_destination_code",
  "LAST DESTINATION CODE MODIFIED BY": "$last_destination_code_modified_by",
  "LAST DESTINATION CODE MODIFIED DATE AND TIME": "$last_destination_code_modified_date_and_time",
  "MASTER BAG DATE & TIME": "$master_bag_date_time",
  "MASTER BAG NO (MMBAG)": "$master_bag_no_mmbag",
  "APPROVAL BAG DATE & TIME": "$approval_bag_date_time",
  "DETAIL BAG NO (DMBAG)": "$detail_bag_no_dmbag",
  "USER - ENTRY BAG": "$user_entry_bag",
  "BAGGING PIC NAME": "$bagging_pic_name",
  "OUTBOUND MANIFEST DATE & TIME": "$outbound_manifest_date_time",
  "OUTBOUND MANIFEST NUMBER": "$outbound_manifest_number",
  "OUTBOUND MANIFEST REMARK": "$outbound_manifest_remark",
  "OUTBOUND MANIFEST STATUS": "$outbound_manifest_status",
  "CONNOTE OUTBOUND MANIFESTED BY": "$connote_outbound_manifested_by",
  "APPROVED OUTBOUND MANIFESTED DATE": "$approved_outbound_manifested_date",
  "OUTBOUND MANIFEST CANCELLED DATE & TIME": "$outbound_manifest_cancelled_date_time",
  "USER - OUTBOUND MANIFEST CANCELLED BY": "$user_outbound_manifest_cancelled_by",
  "OUTBOUND MANIFEST CANCELLED REASON": "$outbound_manifest_cancelled_reason",
  "HANDOVER OUTBOUND DATE & TIME": "$handover_outbound_date_time",
  "HANDOVER OUTBOUND NUMBER": "$handover_outbound_number",
  "USER - HANDOVER OUTBOUND DATA ENTRY": "$user_handover_outbound_data_entry",
  "HANDOVER OUTBOUND PIC NAME": "$handover_outbound_pic_name",
  "HANDOVER OUTBOUND REMARK": "$handover_outbound_remark",
  "HANDOVER OUTBOUND APPROVAL DATE & TIME": "$handover_outbound_approval_date_time",
  "USER - APPROVAL HANDOVER OUTBOUND": "$user_approval_handover_outbound",
  "SMU DATE & TIME": "$smu_date_time",
  "SMU NO": "$smu_no",
  "USER - SMU CREATED BY": "$user_smu_created_by",
  "SURAT MUATAN TYPE": "$surat_muatan_type",
  "FLIGHT NO": "$flight_no",
  "FLIGHT NAME": "$flight_name",
  "SMU AGENT ID": "$smu_agent_id",
  "ACTUAL FLIGHT DATE": "$actual_flight_date",
  "SMU APPROVED DATE & TIME": "$smu_approved_date_time",
  "USER - SMU APPROVED BY": "$user_smu_approved_by",
  "SMU CONFIRMED DATE & TIME": "$smu_confirmed_date_time",
  "USER - SMU CONFIRMED CREATED BY": "$user_smu_confirmed_created_by",
  "SMU CANCELLED DATE & TIME": "$smu_cancelled_date_time",
  "USER - SMU REQUEST CANCELLED BY": "$user_smu_request_cancelled_by",
  "SMU REQUEST CANCELLED REMARK": "$smu_request_cancelled_remark",
  "SMU STATUS": "$smu_status",
  "SMU REMARK": "$smu_remark",
  "TRANSIT MANIFEST DATE & TIME": "$transit_manifest_date_time",
  "TRANSIT MANIFEST NUMBER": "$transit_manifest_number",
  "USER - TRANSIT MANIFEST DATA ENTRY": "$user_transit_manifest_data_entry",
  "APPROVED TRANSIT DATE & TIME": "$approved_transit_date_time",
  "USER - APPROVED TRANSIT MANIFEST": "$user_approved_transit_manifest",
  "TRANSIT CITY CODE": "$transit_city_code",
  "DELIVERED TO CITY DATE & TIME": "$delivered_to_city_date_time",
  "DELIVERED TO WAREHOUSE DATE & TIME": "$delivered_to_warehouse_date_time",
  "HANDOVER INBOUND NUMBER": "$handover_inbound_number",
  "HANDOVER INBOUND DATE & TIME": "$handover_inbound_date_time",
  "USER - HANDOVER INBOUND DATA ENTRY": "$user_handover_inbound_data_entry",
  "HANDOVER INBOUND PIC NAME": "$handover_inbound_pic_name",
  "HANDOVER INBOUND REMARK": "$handover_inbound_remark",
  "HANDOVER INBOUND APPROVAL DATE & TIME": "$handover_inbound_approval_date_time",
  "USER - APPROVAL HANDOVER INBOUND": "$user_approval_handover_inbound",
  "HANDOVER INBOUND CANCELLED DATE & TIME": "$handover_inbound_cancelled_date_time",
  "USER - HANDOVER INBOUND CANCELLED DATA ENTRY": "$user_handover_inbound_cancelled_data_entry",
  "INBOUND MANIFEST CANCELLED REASON": "$inbound_manifest_cancelled_reason",
  "INBOUND MANIFEST DATE & TIME": "$inbound_manifest_date_time",
  "INBOUND MANIFEST NUMBER": "$inbound_manifest_number",
  "USER - INBOUND MANIFEST DATA ENTRY": "$user_inbound_manifest_data_entry",
  "INBOUND MANIFEST REMARK": "$inbound_manifest_remark",
  "RUNSHEET CREATED DATE & TIME": "$runsheet_created_date__time",
  "RUNSHEET NUMBER": "$runsheet_number",
  "RUNSHEET STATUS": "$runsheet_status",
  "RUNSHEET REMARK": "$runsheet_remark",
  "USER - RUNSHEET CREATED BY": "$user_runsheet_created_by",
  "APPROVED RUNSHEET DATE & TIME": "$approved_runsheet_date_time",
  "USER - APPROVAL RUNSHEET BY": "$user_approval_runsheet_by",
  "HANDOVER RUNSHEET DATE & TIME": "$handover_runsheet_date_time",
  "HANDOVER RUNSHEET NUMBER": "$handover_runsheet_number",
  "USER - HANDOVER RUNSHEET CREATED BY": "$user_handover_runsheet_created_by",
  "APPROVED HANDOVER RUNSHEET DATE & TIME": "$approved_handover_runsheet_date_time",
  "USER - APPROVAL HANDOVER RUNSHEET BY": "$user_approval_handover_runsheet_by",
  "HANDOVER RUNSHEET STATUS": "$handover_runsheet_status",
  "DELIVERY ADDRESS - STREET": "$delivery_address_street",
  "DELIVERY ADDRESS - DISTRICT": "$delivery_address_district",
  "DELIVERY ADDRESS - CITY": "$delivery_address_city",
  "DELIVERY ADDRESS - PROVINCE": "$delivery_address_province",
  "DELIVERY ADDRESS - ZIP CODE": "$delivery_address_zip_code",
  "DELIVERY PIC NAME": "$delivery_pic_name",
  "DELIVERY PIC PHONE": "$delivery_pic_phone",
  "INITIAL - POD DATE & TIME": "$initial_pod_date_time",
  "INITIAL - USER POD CREATED BY": "$initial_user_pod_created_by",
  "INITIAL - POD STATUS CODE": "$initial_pod_status_code",
  "INITIAL - POD STATUS NAME": "$initial_pod_status_name",
  "INITIAL - POD SUCCESS STATUS": "$initial_pod_success_status",
  "INITIAL - POD REMARK": "$initial_pod_remark",
  "INITIAL - DELIVERY COURIER ID": "$initial_delivery_courier_id",
  "INITIAL - DELIVERY COURIER NAME": "$initial_delivery_courier_name",
  "INITIAL - DELIVERY VEHICLE": "$initial_delivery_vehicle",
  "UNDELIVERED - POD DATE & TIME": "$undelivered_pod_date_time",
  "UNDELIVERED - USER POD CREATED BY": "$undelivered_user_pod_created_by",
  "UNDELIVERED - POD STATUS CODE": "$undelivered_pod_status_code",
  "UNDELIVERED - POD STATUS NAME": "$undelivered_pod_status_name",
  "UNDELIVERED - POD SUCCESS STATUS": "$undelivered_pod_success_status",
  "UNDELIVERED - POD REMARK": "$undelivered_pod_remark",
  "UNDELIVERED - DELIVERY COURIER ID": "$undelivered_delivery_courier_id",
  "UNDELIVERED - DELIVERY COURIER NAME": "$undelivered_delivery_courier_name",
  "UNDELIVERED - DELIVERY VEHICLE": "$undelivered_delivery_vehicle",
  "REDELIVERY - POD DATE & TIME": "$redelivery_pod_date_time",
  "REDELIVERY - USER POD CREATED BY": "$redelivery_user_pod_created_by",
  "REDELIVERY - POD STATUS CODE": "$redelivery_pod_status_code",
  "REDELIVERY - POD STATUS NAME": "$redelivery_pod_status_name",
  "REDELIVERY - POD SUCCESS STATUS": "$redelivery_pod_success_status",
  "REDELIVERY - POD REMARK": "$redelivery_pod_remark",
  "REDELIVERY - DELIVERY COURIER ID": "$redelivery_delivery_courier_id",
  "REDELIVERY - DELIVERY COURIER NAME": "$redelivery_delivery_courier_name",
  "REDELIVERY - DELIVERY VEHICLE": "$redelivery_delivery_vehicle",
  "FINAL - CONNOTE POD STATUS DATE & TIME": "$final_connote_pod_status_date_time",
  "FINAL - CONNOTE POD CREATED BY": "$final_connote_pod_created_by",
  "FINAL - POD STATUS CODE": "$final_pod_status_code",
  "FINAL - POD STATUS NAME": "$final_pod_status_name",
  "FINAL - POD SUCCESS STATUS": "$final_pod_success_status",
  "FINAL - POD REMARK": "$final_pod_remark",
  "FINAL - DELIVERY COURIER ID": "$final_delivery_courier_id",
  "FINAL - DELIVERY COURIER NAME": "$final_delivery_courier_name",
  "FINAL - DELIVERY VEHICLE": "$final_delivery_vehicle",
  "TOTAL ACTUAL DELIVERY DAYS": "$total_actual_delivery_days",
  "CONNOTE BATCHING STATUS": "$connote_batching_status",
  "CONNOTE - BMS STATUS": "$status_connote",
  "CONNOTE RECEIVED & SORTED - LAST MODIFIED DATE & TIME": "$connote_received_sorted_last_modified_date_time",
  "CONNOTE RECEIVED & SORTED - LAST MODIFIED BY": "$connote_received_sorted_last_modified_by",
  "CONNOTE READY TO BE INVOICED - LAST MODIFIED DATE & TIME": "$connote_ready_to_be_invoiced_last_modified_date_time",
  "CONNOTE READY TO BE INVOICED - LAST MODIFIED BY": "$connote_ready_to_be_invoiced_last_modified_by",
  "PROFORMA INVOICE NUMBER": "$proforma_invoice_number",
  "PROFORMA INVOICE - INITIAL DATE - LAST MODIFIED DATE & TIME": "$proforma_invoice_initial_date_last_modified_date_time",
  "PROFORMA INVOICE - INITIAL DATE - LAST MODIFIED BY": "$proforma_invoice_initial_date_last_modified_by",
  "PROFORMA INVOICE - APPROVED DATE - LAST MODIFIED DATE & TIME": "$proforma_invoice_approved_date_last_modified_date_time",
  "PROFORMA INVOICE - APPROVED DATE - LAST MODIFIED BY": "$proforma_invoice_approved_date_last_modified_by",
  "INVOICE NUMBER": "$invoice_number",
  "INVOICE DATE": "$invoice_date",
  "SORTER ID": "$sorted_id",
  "SORTER NAME": "$sorter_name",
  "INVOICING OFFICER ID": "$invoicing_officer_id",
  "INVOICING OFFICER NAME": "$invoicing_officer_name",
  "TAX ADMINISTRATOR ID": "$tax_administrator_id",
  "TAX ADMINISTRATOR NAME": "$tax_administrator_name",
  "MESSENGER ID": "$messenger_id",
  "MESSENGER NAME": "$messenger_name",
  "COLLECTOR ID": "$collector_id",
  "COLLECTOR NAME": "$collector_name",
  "COD AMOUNT": "$cod_amount",
  "COD FEE INV": "$cod_fee_inv",
  "CONSIGNEE PIC PHONE": "$consignee_pic_phone",
  "CONTACT INFORMATION - ADDRESS_CITY": "$contact_information_address_city",
  "CONTACT INFORMATION - ADDRESS_KECAMATAN": "$contact_information_address_kecamatan",
  "CONTACT INFORMATION - ADDRESS_KELURAHAN": "$contact_information_address_kelurahan",
  "CONTACT INFORMATION - ADDRESS_LATITUDE": "$contact_information_address_latitude",
  "CONTACT INFORMATION - ADDRESS_LONGITUDE": "$contact_information_address_longitude",
  "CONTACT INFORMATION - ADDRESS_STREET": "$contact_information_address_street",
  "CONTACT INFORMATION - ADDRESS_ZIP CODE": "$contact_information_address_zip_code",
  "CUSTOMER STATUS": "$customer_status",
  "JOURNAL BATCH NUMBER": "$journal_batch_number",
  "NPWP ID": "$npwp_id",
  "NPWP NAME": "$npwp_name",
  "NPWP ADDRESS": "$npwp_address",
  "POSTING DATE": "$posting_date",
  "POSTING STATUS": "$posting_status",
  "REVISED/CANCELLED JOURNAL BATCH NUMBER": "$revised_cancelled_journal_batch_number",
  "REVISED/CANCELLED POSTING DATE": "$revised_cancelled_posting_date",
  "REVISED/CANCELLED POSTING STATUS": "$revised_cancelled_posting_status",
  "REVISED/CANCELLED VOUCHER NUMBER": "$revised_cancelled_voucher_number",
  "REVISED INVOICE DATE": "$revised_invoice_date",
  "REVISED INVOICE NUMBER": "$revised_invoice_number",
  "SERVICE CODE": "$service_code",
  "SHIPPER PIC PHONE": "$shipper_pic_phone",
  "USER - PICK UP REQUEST APPROVED BY": "$user_pick_up_request_approved_by",
  "VOUCHER NUMBER": "$voucher_number",
  "COD CATEGORY - CCNC": "$cod_category_ccnc",
  "PUBLISH FREIGHT CHARGE - CCNC": "$publish_freight_charge_ccnc_decimal",
  "VAT1 - CCNC": "$vat1_ccnc_decimal",
  "PERCENT DISC - CCNC": "$percent_disc_ccnc_decimal",
  "DISCOUNT AMOUNT - CCNC": "$discount_amount_ccnc_decimal",
  "NET FREIGHT CHARGE - CCNC": "$net_freight_charge_ccnc_decimal",
  "VAT1 NET FREIGHT CHARGE - CCNC": "$vat1_net_freight_charge_ccnc_decimal",
  "PACKING FEE - CCNC": "$packing_fee_ccnc_decimal",
  "SURCHARGE - CCNC": "$surcharge_ccnc_decimal",
  "INSURANCE - CCNC": "$insurance_ccnc_decimal",
  "RETURN CHARGE - CCNC": "$return_charge_ccnc_decimal",
  "VAT1 RT - CCNC": "$vat1_rt_ccnc_decimal",
  "COD AMT - CCNC": "$cod_amt_ccnc_decimal",
  "PERCENT COD FEE - CCNC": "$percent_cod_fee_ccnc_decimal",
  "COD FEE INCL VAT2 - CCNC": "$cod_fee_incl_vat2_ccnc_decimal",
  "DEDUCTION - CCNC": "$deduction_ccnc_decimal",
  "NET COD AMT - CCNC": "$net_cod_amt_ccnc_decimal",
  "PAYMENT NO - CCNC": "$payment_no_ccnc",
  "PAYMENT TRF DATE - CCNC": "$payment_trf_date_ccnc",
  "PAYMENT TYPE - CCNC": "$payment_type_ccnc",
  "LAST STATUS ORION - CONNOTE UPDATE": "$last_status_orion_connote_update",
  "LAST UPDATED DATE & TIME - CONNOTE UPDATE": "$last_updated_date_time_connote_update",
  "FLAGGING DISCOUNT CALCULATION": "$flagging_discount_calculation",
  "DATE & TIME DISCOUNT CALCULATION": "$date_time_discount_calculation",
  "FLAGGING MFEE NA CALCULATION": "$flagging_mfee_na_calculation",
  "DATE & TIME MFEE NA CALCULATION": "$date_time_mfee_na_calculation",
  "FLAGGING INSURANCE CALCULATION": "$flagging_insurance_calculation",
  "DATE & TIME INSURANCE CALCULATION": "$date_time_insurance_calculation",
  "SERVICE TYPE": "$service_type",
  "SERVICE GROUP": "$service_group",
  "COD FEE INVOICE NUMBER": "$invoice_number_cod",
  "COD FEE INVOICE DATE": "$invoice_date_cod",
  "SERVICE CODE - CCNC": "$recod_d_serv_code",
  "HUB COURIER ID - CCNC": "$recod_d_dest_code",
  "MANAGEMENT FEE ID": "$management_fee_id",
  "MANAGEMENT FEE NAME": "$management_fee_name",
  "OPERATIONAL AMOUNT": "$operational_amunt",
  "INCENTIVE AMOUNT": "$incentive_amount",
  "ROYALTY AMOUNT": "$royalty_amount",

  // Sub Agen
  "ORIGIN - ENTITY TYPE": "$origin_entity_type",
  "ORIGIN - MANAGING ENTITY ID": "$origin_managing_entity_id",
  "ORIGIN - MANAGING ENTITY NAME": "$origin_managing_entity_name",
  "DESTINATION - ENTITY TYPE": "$destination_entity_type",
  "DESTINATION - MANAGING ENTITY ID": "$destination_managing_entity_id",
  "DESTINATION - MANAGING ENTITY NAME": "$destination_managing_entity_name",
  "DESTINATION - MANAGING ENTITY PARENT ID": "$destination_managing_entity_parent_id",
  "DESTINATION - MANAGING ENTITY PARENT NAME": "$destination_managing_entity_parent_name",
  "COMMISSION RATE - NA CASHLESS": "$fee_rate_na_cashless",
  "COMMISSION TYPE - NA CASHLESS": "$commission_type_na_cashless",
  "DOC NUMBER - NA CASHLESS": "$ho_no",

  // QC Report (Sementara)
  "P - DATE": "$p_date",
  "IMPORT TAX SLIP - DATE": "$import_tax_slip_date"
};

if (payload.hasOwnProperty("column_type")) {
  if (payload.column_type == "Cashless") {
      listColumn = {
          "BRANCH ID": "$branch_id",
          "BRANCH NAME": "$branch_name",
          "BRANCH TYPE": "$branch_type",
          "AWB NUMBER": "$awb_number",
          "AWB DATE": "$awb_date",
          "CUSTOMER ID": "$customer_id",
          "CUSTOMER NAME": "$customer_name",
          "LOCAL PARENT ID": "$local_parent_id",
          "LOCAL PARENT ID NAME": "$local_parent_name",
          "NATIONAL PARENT ID": "$national_parent_id",
          "NATIONAL PARENT ID NAME": "$national_parent_name",
          "CUSTOMER TYPE": "$customer_type",
          "CUSTOMER TYPE NAME": "$customer_type_name",
          "INDUSTRY TYPE CODE": "$industry_type_code",
          "INDUSTRY TYPE NAME": "$industry_type_name",
          "NA PRINCIPAL": "$na_principal",
          "IS CASHLESS?": "$is_cashless",
          "ORIGIN SYS CODE (ORION)": "$origin_sys_code",
          "UPDATED ORIGIN CODE": "$updated_origin_code",
          "DESTINATION SYS CODE (ORION)": "$destination_sys_code",
          "UPDATED DESTINATION CODE": "$updated_destination_code",
          "SERVICE TYPE": "$service_type",
          "SERVICE CODE": "$service_code",
          "UPDATED SERVICE TYPE": "$updated_service_type",
          "QUANTITY": "$quantity",
          "WEIGHT (KG)": "$weight_kg",
          "UPDATED WEIGHT (KGS)": "$updated_weight_kgs",
          "GOODS VALUE": "$goods_value",
          "ORIGINAL AMOUNT": "$original_amount_number",
          "DISCOUNT AMOUNT (AWB)": "$discount_amount_awb_number",
          "ADJUSTED AMOUNT": "$adjusted_amount_number",
          "PACKING": "$packing_number",
          "SURCHARGE": "$surcharge_number",
          "OTHER CHARGES": "$other_charges_number",
          "TOTAL PACKING & CHARGES": "$total_packing_charges_number",
          "TOTAL AMOUNT AFTER DISCOUNT & CHARGES (DPP)": "$total_amount_after_discount_charges_dpp",
          "FINAL - CONNOTE POD STATUS DATE & TIME": "$final_connote_pod_status_date_time",
          "FINAL - CONNOTE POD CREATED BY": "$final_connote_pod_created_by",
          "FINAL - POD STATUS CODE": "$final_pod_status_code",
          "FINAL - POD SUCCESS STATUS": "$final_pod_success_status",
          "CONNOTE - BMS STATUS": "$status_connote",
          "INVOICE NUMBER": "$invoice_number",
          "INVOICE DATE": "$invoice_date",
          "ORIGIN - ENTITY TYPE": "$origin_entity_type",
          "ORIGIN - MANAGING ENTITY ID": "$origin_managing_entity_id",
          "ORIGIN - MANAGING ENTITY NAME": "$origin_managing_entity_name",
          "COMMISSION RATE - NA CASHLESS": "$fee_rate_na_cashless",
          "COMMISSION TYPE - NA CASHLESS": "$commission_type_na_cashless",
          "DOC NUMBER - NA CASHLESS": "$ho_no",
          "CONNOTE CANCEL": "$connote_cancel",
          "DATE & TIME DISCOUNT CALCULATION": "$date_time_discount_calculation",
          "FLAGGING DISCOUNT CALCULATION": "$flagging_discount_calculation"
      }
  };

  if (payload.column_type == "Unbilled") {
      listColumn = {
          "_id": 0,
          "BRANCH ID": "$branch_id",
          "AWB DATE": "$awb_date",
          "AWB NUMBER": "$awb_number",
          "CUSTOMER TYPE": "$customer_type",
          "NATIONAL PARENT ID": "$national_parent_id",
          "NATIONAL PARENT ID NAME": "$national_parent_name",
          "LOCAL PARENT ID": "$local_parent_id",
          "LOCAL PARENT ID NAME": "$local_parent_name",
          "CUSTOMER ID": "$customer_id",
          "CUSTOMER NAME": "$customer_name",
          "ORIGIN BRANCH ID": "$origin_branch_id",
          "DESTINATION BRANCH ID": "$destination_branch_id",
          "ORIGIN SYS CODE (ORION)": "$origin_sys_code",
          "DESTINATION SYS CODE (ORION)": "$destination_sys_code",
          "ORIGIN ZIP CODE (ORION)": "$origin_zip_code_orion",
          "DESTINATION ZIP CODE (ORION)": "$destination_zip_code_orion",
          "ORIGIN ID": "$origin_id",
          "ORIGIN ID NAME": "$origin_name",
          "DESTINATION ID": "$destination_id",
          "DESTINATION ID NAME": "$destination_name",
          "ORIGIN ZIP CODE (BMS)": "$origin_zip_code_bms",
          "DESTINATION ZIP CODE (BMS)": "$destination_zip_code_bms",
          "ACTUAL WEIGHT": "$actual_weight",
          "HEIGHT": "$height",
          "WIDTH": "$width",
          "LENGTH": "$length",
          "VOLUMETRIC WEIGHT (H X W X L)": "$volumetric_weight_h_x_w_x_l",
          "QUANTITY": "$quantity",
          "GOODS TYPE": "$goods_type",
          "GOODS VALUE": "$goods_value",
          "PAYMENT TYPE": "$payment_type",
          "CONNOTE CREATED DATE & TIME": "$connote_created_date_time",
          "OUTBOUND MANIFEST STATUS": "$outbound_manifest_status",
          "OUTBOUND MANIFEST DATE & TIME": "$outbound_manifest_date_time",
          "CONNOTE OUTBOUND MANIFESTED BY": "$connote_outbound_manifested_by",
          "HANDOVER INBOUND DATE & TIME": "$handover_inbound_date_time",
          "USER - HANDOVER INBOUND DATA ENTRY": "$user_handover_inbound_data_entry",
          "RUNSHEET CREATED DATE & TIME": "$runsheet_created_date__time",
          "FINAL - CONNOTE POD STATUS DATE & TIME": "$final_connote_pod_status_date_time",
          "FINAL - CONNOTE POD CREATED BY": "$final_connote_pod_created_by",
          "FINAL - POD STATUS CODE": "$final_pod_status_code",
          "FINAL - POD STATUS NAME": "$final_pod_status_name",
          "SERVICE TYPE": "$service_type",
          "ORIGINAL AMOUNT": "$original_amount_number",
          "DISCOUNT AMOUNT (AWB)": "$discount_amount_awb_number",
          "ADJUSTED AMOUNT": "$adjusted_amount_number",
          "PACKING": "$packing_number",
          "SURCHARGE": "$surcharge_number",
          "OTHER CHARGES": "$other_charges_number",
          "ORIGINAL INSURANCE ADMIN": "$original_insurance_admin",
          "ORIGINAL INSURANCE PREMI": "$original_insurance_premi",
          "ADJUSTED INSURANCE PREMI": "$adjusted_insurance_premi_number",
          "ADJUSTED INSURANCE ADMIN": "$adjusted_insurance_admin_number",
          "ADJUSTED INSURANCE PREMI": "$adjusted_insurance_premi_number",
          "CONNOTE - BMS STATUS": "$status_connote",
          "TOTAL AMOUNT AFTER DISCOUNT & CHARGES (DPP)": "$total_amount_after_discount_charges_dpp",
      }
  };

  if (payload.column_type == "Unbilled Total Revenue") {
    listColumn = {
        "_id": 0,
        "AWB NUMBER": "$awb_number",
        "AWB DATE": "$awb_date",
        "BRANCH ID": "$branch_id",
        "CUSTOMER ID": "$customer_id",
        "ORIGINAL AMOUNT": "$original_amount_number",
        "SURCHARGE": "$surcharge_number",
        "PACKING": "$packing_number",
        "OTHER CHARGES": "$other_charges_number",
        "DISCOUNT AMOUNT (AWB)": "$discount_amount_awb_number",
        "ADJUSTED AMOUNT": "$adjusted_amount_number",
        "CONNOTE - BMS STATUS": "$status_connote",
        "INVOICE DATE": "$invoice_date",
    }
};
};