var listColumnGet = {
  "_id": 0,
  "branch_id": 1,
  "branch_type": 1,
  "awb_date": 1,
  "awb_number": 1,
  "customer_id": 1,
  "customer_name": 1,
  "local_parent_id": 1,
  "local_parent_name": 1,
  "national_parent_id": 1,
  "national_parent_name": 1,
  "branch_name": 1,
  "site_id": 1,
  "site_name": 1,
  "customer_type": 1,
  "customer_type_name": 1,
  "industry_type_code": 1,
  "industry_type_name": 1,
  "contract_number": 1,
  "contract_validity_period_from_date": 1,
  "contract_validity_period_to_date": 1,
  "check_box_billed_by_site": 1,
  "flagging_multi_or_local_branch": 1,
  "na_principal": 1,
  "is_cashless": 1,
  "term_of_payment": 1,
  "currency": 1,
  "generate_mass_standard_invoice": 1,
  "creation_date_and_time": 1,
  "ccrf_last_update_date_and_time_the_core": 1,
  "origin_sys_code": 1,
  "origin_city_name": 1,
  "origin_zip_code_orion": 1,
  "destination_sys_code": 1,
  "destination_city_name": 1,
  "destination_zip_code_orion": 1,
  "route_code": 1,
  "origin_branch_id": 1,
  "origin_id": 1,
  "origin_name": 1,
  "origin_urban_village_name": 1,
  "origin_district_name": 1,
  "origin_zone": 1,
  "origin_city_name": 1,
  "origin_province_name": 1,
  "origin_zip_code_bms": 1,
  "destination_branch_id": 1,
  "destination_id": 1,
  "destination_name": 1,
  "destination_urban_village_name": 1,
  "destination_district_name": 1,
  "destination_zone": 1,
  "destination_city_name": 1,
  "destination_province_name": 1,
  "destination_zip_code_bms": 1,
  "origin_destination_id": 1,
  "origin_rate_card_id": 1,
  "origin_rate_card_id_name": 1,
  "destination_rate_card_id": 1,
  "destination_rate_card_id_name": 1,
  "quantity": 1,
  "weight_kg": 1,
  "weight_gram": 1,
  "height": 1,
  "width": 1,
  "length": 1,
  "volumetric_weight_h_x_w_x_l": 1,
  "shipper_name": 1,
  "shipper_address_street": 1,
  "shipper_address_district": 1,
  "shipper_address_city": 1,
  "shipper_address_province": 1,
  "shipper_address_zip_code": 1,
  "shipper_pic_name": 1,
  "consignee_name": 1,
  "consignee_address_street": 1,
  "consignee_address_district": 1,
  "consignee_address_city": 1,
  "consignee_address_province": 1,
  "consignee_address_zip_code": 1,
  "consignee_pic_name": 1,
  "goods_type": 1,
  "goods_description": 1,
  "goods_value": 1,
  "original_amount_number": 1,
  "original_amount_per_kg": 1,
  "pricing_combination_id": 1,
  "pricing_model_name": 1,
  "discount_amount_awb_number": 1,
  "adjusted_amount_number": 1,
  "packing_flag": 1,
  "packing_number": 1,
  "surcharge_number": 1,
  "other_charges_number": 1,
  "total_packing_charges_number": 1,
  "total_amount_after_discount_charges_dpp": 1,
  "vat_freight": 1,
  "insurance_flag": 1,
  "insurance_id": 1,
  "insurance_number": 1,
  "original_insurance_admin": 1,
  "original_insurance_premi": 1,
  "insurance_charge": 1,
  "adjusted_insurance_premi_number": 1,
  "adjusted_insurance_admin_number": 1,
  "total_adjusted_insurance_amount": 1,
  "paid_amount": 1,
  "payment_type": 1,
  "cod_flag": 1,
  "persentase_cod_fee": 1,
  "cod_fee_amount": 1,
  "cod_fee_zone": 1,
  "cod_amount_paid_to_customer": 1,
  "difference_cod_amount_paid_to_customer": 1,
  "nota_tagihan_cod_paid_to_customer": 1,
  "tanggal_pembayaran_cod": 1,
  "periode_transaksi_cod": 1,
  "tracking_number_id": 1,
  "awb_return_number": 1,
  "connote_remark": 1,
  "handling_connote_type": 1,
  "econnote_flag": 1,
  "connote_must_be_attached_flag": 1,
  "delivery_order_flag": 1,
  "user_approval_connote_data_entry": 1,
  "connote_created_date_time": 1,
  "approval_connote_data_entry_date_time": 1,
  "connote_cancel": 1,
  "connote_cancel_reason": 1,
  "connote_hold": 1,
  "connote_hold_reason": 1,
  "pick_up_by_branch": 1,
  "pick_up_request_number": 1,
  "pick_up_order_id": 1,
  "pick_up_request_date_time": 1,
  "user_pick_up_request_created_by": 1,
  "pick_up_request_approved_date_time": 1,
  "pick_up_request_ready_date_time": 1,
  "user_request_pick_up_ready_created_by": 1,
  "pick_up_confirmed_date_time": 1,
  "user_pick_up_confirmed_created_by": 1,
  "re_pick_up_date_time": 1,
  "re_pick_up_courier_id": 1,
  "re_pick_up_courier_name": 1,
  "pick_up_request_cancelled_date_time": 1,
  "user_pick_up_request_cancelled_by": 1,
  "pick_up_request_cancelled_remark": 1,
  "pick_up_date_time": 1,
  "pick_up_courier_id": 1,
  "pick_up_courier_name": 1,
  "pick_up_address_street": 1,
  "pick_up_address_district": 1,
  "pick_up_address_city": 1,
  "pick_up_address_province": 1,
  "pick_up_address_zip_code": 1,
  "pick_up_pic_name": 1,
  "pick_up_pic_phone": 1,
  "pick_up_status": 1,
  "pick_up_vehicle": 1,
  "pick_up_special_instruction": 1,
  "pick_up_request_received_date_time": 1,
  "user_pick_up_request_received_by": 1,
  "sla_days": 1,
  "sla_date": 1,
  "receiving_checking_connote_date_time": 1,
  "receiving_checking_connote_no": 1,
  "receiving_checking_connote_remark": 1,
  "receiver_checker_connote_pic_name": 1,
  "user_receiving_checking_connote": 1,
  "user_approval_receiving_checking_connote": 1,
  "updated_weight_yes_no": 1,
  "updated_weight_kgs": 1,
  "updated_height": 1,
  "updated_width": 1,
  "updated_length": 1,
  "updated_volumetric_weight_h_x_w_x_l": 1,
  "actual_weight": 1,
  "last_weight_modified_by": 1,
  "last_weight_modified_date_and_time": 1,
  "updated_service_type_yes_no": 1,
  "updated_service_type": 1,
  "last_service_type_modified_by": 1,
  "last_service_type_modified_date_and_time": 1,
  "updated_origin_code_yes_no": 1,
  "updated_origin_code": 1,
  "last_origin_code_modified_by": 1,
  "last_origin_code_modified_date_and_time": 1,
  "updated_destination_code_yes_no": 1,
  "updated_destination_code": 1,
  "last_destination_code_modified_by": 1,
  "last_destination_code_modified_date_and_time": 1,
  "master_bag_date_time": 1,
  "master_bag_no_mmbag": 1,
  "approval_bag_date_time": 1,
  "detail_bag_no_dmbag": 1,
  "user_entry_bag": 1,
  "bagging_pic_name": 1,
  "outbound_manifest_date_time": 1,
  "outbound_manifest_number": 1,
  "outbound_manifest_remark": 1,
  "outbound_manifest_status": 1,
  "connote_outbound_manifested_by": 1,
  "approved_outbound_manifested_date": 1,
  "outbound_manifest_cancelled_date_time": 1,
  "user_outbound_manifest_cancelled_by": 1,
  "outbound_manifest_cancelled_reason": 1,
  "handover_outbound_date_time": 1,
  "handover_outbound_number": 1,
  "user_handover_outbound_data_entry": 1,
  "handover_outbound_pic_name": 1,
  "handover_outbound_remark": 1,
  "handover_outbound_approval_date_time": 1,
  "user_approval_handover_outbound": 1,
  "smu_date_time": 1,
  "smu_no": 1,
  "user_smu_created_by": 1,
  "surat_muatan_type": 1,
  "flight_no": 1,
  "flight_name": 1,
  "smu_agent_id": 1,
  "actual_flight_date": 1,
  "smu_approved_date_time": 1,
  "user_smu_approved_by": 1,
  "smu_confirmed_date_time": 1,
  "user_smu_confirmed_created_by": 1,
  "smu_cancelled_date_time": 1,
  "user_smu_request_cancelled_by": 1,
  "smu_request_cancelled_remark": 1,
  "smu_status": 1,
  "smu_remark": 1,
  "transit_manifest_date_time": 1,
  "transit_manifest_number": 1,
  "user_transit_manifest_data_entry": 1,
  "approved_transit_date_time": 1,
  "user_approved_transit_manifest": 1,
  "transit_city_code": 1,
  "delivered_to_city_date_time": 1,
  "delivered_to_warehouse_date_time": 1,
  "handover_inbound_number": 1,
  "handover_inbound_date_time": 1,
  "user_handover_inbound_data_entry": 1,
  "handover_inbound_pic_name": 1,
  "handover_inbound_remark": 1,
  "handover_inbound_approval_date_time": 1,
  "user_approval_handover_inbound": 1,
  "handover_inbound_cancelled_date_time": 1,
  "user_handover_inbound_cancelled_data_entry": 1,
  "inbound_manifest_cancelled_reason": 1,
  "inbound_manifest_date_time": 1,
  "inbound_manifest_number": 1,
  "user_inbound_manifest_data_entry": 1,
  "inbound_manifest_remark": 1,
  "runsheet_created_date__time": 1,
  "runsheet_number": 1,
  "runsheet_status": 1,
  "runsheet_remark": 1,
  "user_runsheet_created_by": 1,
  "approved_runsheet_date_time": 1,
  "user_approval_runsheet_by": 1,
  "handover_runsheet_date_time": 1,
  "handover_runsheet_number": 1,
  "user_handover_runsheet_created_by": 1,
  "approved_handover_runsheet_date_time": 1,
  "user_approval_handover_runsheet_by": 1,
  "handover_runsheet_status": 1,
  "delivery_address_street": 1,
  "delivery_address_district": 1,
  "delivery_address_city": 1,
  "delivery_address_province": 1,
  "delivery_address_zip_code": 1,
  "delivery_pic_name": 1,
  "delivery_pic_phone": 1,
  "initial_pod_date_time": 1,
  "initial_user_pod_created_by": 1,
  "initial_pod_status_code": 1,
  "initial_pod_status_name": 1,
  "initial_pod_success_status": 1,
  "initial_pod_remark": 1,
  "initial_delivery_courier_id": 1,
  "initial_delivery_courier_name": 1,
  "initial_delivery_vehicle": 1,
  "undelivered_pod_date_time": 1,
  "undelivered_user_pod_created_by": 1,
  "undelivered_pod_status_code": 1,
  "undelivered_pod_status_name": 1,
  "undelivered_pod_success_status": 1,
  "undelivered_pod_remark": 1,
  "undelivered_delivery_courier_id": 1,
  "undelivered_delivery_courier_name": 1,
  "undelivered_delivery_vehicle": 1,
  "redelivery_pod_date_time": 1,
  "redelivery_user_pod_created_by": 1,
  "redelivery_pod_status_code": 1,
  "redelivery_pod_status_name": 1,
  "redelivery_pod_success_status": 1,
  "redelivery_pod_remark": 1,
  "redelivery_delivery_courier_id": 1,
  "redelivery_delivery_courier_name": 1,
  "redelivery_delivery_vehicle": 1,
  "final_connote_pod_status_date_time": 1,
  "final_connote_pod_created_by": 1,
  "final_pod_status_code": 1,
  "final_pod_status_name": 1,
  "final_pod_success_status": 1,
  "final_pod_remark": 1,
  "final_delivery_courier_id": 1,
  "final_delivery_courier_name": 1,
  "final_delivery_vehicle": 1,
  "total_actual_delivery_days": 1,
  "connote_batching_status": 1,
  "status_connote": 1,
  "connote_received_sorted_last_modified_date_time": 1,
  "connote_received_sorted_last_modified_by": 1,
  "connote_ready_to_be_invoiced_last_modified_date_time": 1,
  "connote_ready_to_be_invoiced_last_modified_by": 1,
  "proforma_invoice_number": 1,
  "proforma_invoice_initial_date_last_modified_date_time": 1,
  "proforma_invoice_initial_date_last_modified_by": 1,
  "proforma_invoice_approved_date_last_modified_date_time": 1,
  "proforma_invoice_approved_date_last_modified_by": 1,
  "invoice_number": 1,
  "invoice_date": 1,
  "sorted_id": 1,
  "sorter_name": 1,
  "invoicing_officer_id": 1,
  "invoicing_officer_name": 1,
  "tax_administrator_id": 1,
  "tax_administrator_name": 1,
  "messenger_id": 1,
  "messenger_name": 1,
  "collector_id": 1,
  "collector_name": 1,
  "cod_amount": 1,
  "cod_fee_inv": 1,
  "consignee_pic_phone": 1,
  "contact_information_address_city": 1,
  "contact_information_address_kecamatan": 1,
  "contact_information_address_kelurahan": 1,
  "contact_information_address_latitude": 1,
  "contact_information_address_longitude": 1,
  "contact_information_address_street": 1,
  "contact_information_address_zip_code": 1,
  "customer_status": 1,
  "journal_batch_number": 1,
  "npwp_id": 1,
  "npwp_name": 1,
  "npwp_address": 1,
  "posting_date": 1,
  "posting_status": 1,
  "revised_cancelled_journal_batch_number": 1,
  "revised_cancelled_posting_date": 1,
  "revised_cancelled_posting_status": 1,
  "revised_cancelled_voucher_number": 1,
  "revised_invoice_date": 1,
  "revised_invoice_number": 1,
  "service_code": 1,
  "shipper_pic_phone": 1,
  "user_pick_up_request_approved_by": 1,
  "voucher_number": 1,
  "cod_category_ccnc": 1,
  "publish_freight_charge_ccnc_decimal": 1,
  "vat1_ccnc_decimal": 1,
  "percent_disc_ccnc_decimal": 1,
  "discount_amount_ccnc_decimal": 1,
  "net_freight_charge_ccnc_decimal": 1,
  "vat1_net_freight_charge_ccnc_decimal": 1,
  "packing_fee_ccnc_decimal": 1,
  "surcharge_ccnc_decimal": 1,
  "insurance_ccnc_decimal": 1,
  "return_charge_ccnc_decimal": 1,
  "vat1_rt_ccnc_decimal": 1,
  "cod_amt_ccnc_decimal": 1,
  "percent_cod_fee_ccnc_decimal": 1,
  "cod_fee_incl_vat2_ccnc_decimal": 1,
  "deduction_ccnc_decimal": 1,
  "net_cod_amt_ccnc_decimal": 1,
  "payment_no_ccnc": 1,
  "payment_trf_date_ccnc": 1,
  "payment_type_ccnc": 1,
  "last_status_orion_connote_update": 1,
  "last_updated_date_time_connote_update": 1,
  "flagging_discount_calculation": 1,
  "date_time_discount_calculation": 1,
  "flagging_mfee_na_calculation": 1,
  "date_time_mfee_na_calculation": 1,
  "flagging_insurance_calculation": 1,
  "date_time_insurance_calculation": 1,
  "service_type": 1,
  "service_group": 1,
  "invoice_number_cod": 1,
  "invoice_date_cod": 1,
  "recod_d_serv_code": 1,
  "recod_d_dest_code": 1,
  "management_fee_id": 1,
  "management_fee_name": 1,
  "operational_amunt": 1,
  "incentive_amount": 1,
  "royalty_amount": 1,

  // Sub Agen
  "origin_entity_type": 1,
  "origin_managing_entity_id": 1,
  "origin_managing_entity_name": 1,
  "destination_entity_type": 1,
  "destination_managing_entity_id": 1,
  "destination_managing_entity_name": 1,
  "destination_managing_entity_parent_id": 1,
  "destination_managing_entity_parent_name": 1,
  "fee_rate_na_cashless": 1,
  "commission_type_na_cashless": 1,
  "ho_no": 1,

  // QC Report (Sementara)
  "p_date": 1,
  "import_tax_slip_date": 1
};

if (payload.hasOwnProperty("column_type")) {
  if (payload.column_type == "Cashless") {
      listColumnGet = {
          "branch_id": 1,
          "branch_name": 1,
          "branch_type": 1,
          "awb_number": 1,
          "awb_date": 1,
          "customer_id": 1,
          "customer_name": 1,
          "local_parent_id": 1,
          "local_parent_name": 1,
          "national_parent_id": 1,
          "national_parent_name": 1,
          "customer_type": 1,
          "customer_type_name": 1,
          "na_principal": 1,
          "is_cashless": 1,
          "origin_sys_code": 1,
          "updated_origin_code": 1,
          "destination_sys_code": 1,
          "updated_destination_code": 1,
          "service_type": 1,
          "updated_service_type": 1,
          "quantity": 1,
          "weight_kg": 1,
          "updated_weight_kgs": 1,
          "goods_value": 1,
          "original_amount_number": {
              "$cond": {
                  "if": { "$eq": ["$original_amount_number", null] },
                  "then": "0",
                  "else": { "$toString": "$original_amount_number" }
              }
          },
          "discount_amount_awb_number": {
              "$cond": {
                  "if": { "$eq": ["$discount_amount_awb_number", null] },
                  "then": "0",
                  "else": { "$toString": "$discount_amount_awb_number" }
              }
          },
          "adjusted_amount_number": {
              "$cond": {
                  "if": { "$eq": ["$adjusted_amount_number", null] },
                  "then": "0",
                  "else": { "$toString": "$adjusted_amount_number" }
              }
          },
          "packing_number": {
              "$cond": {
                  "if": { "$eq": ["$packing_number", null] },
                  "then": "0",
                  "else": { "$toString": "$packing_number" }
              }
          },
          "surcharge_number": {
              "$cond": {
                  "if": { "$eq": ["$surcharge_number", null] },
                  "then": "0",
                  "else": { "$toString": "$surcharge_number" }
              }
          },
          "other_charges_number": {
              "$cond": {
                  "if": { "$eq": ["$other_charges_number", null] },
                  "then": "0",
                  "else": { "$toString": "$other_charges_number" }
              }
          },
          "total_packing_charges_number": {
              "$cond": {
                  "if": { "$eq": ["$total_packing_charges_number", null] },
                  "then": "0",
                  "else": { "$toString": "$total_packing_charges_number" }
              }
          },
          "total_amount_after_discount_charges_dpp": 1,
          "final_connote_pod_status_date_time": 1,
          "final_connote_pod_created_by": 1,
          "final_pod_status_code": 1,
          "final_pod_success_status": 1,
          "status_connote": 1,
          "invoice_number": 1,
          "invoice_date": 1,
          "origin_entity_type": 1,
          "origin_managing_entity_id": 1,
          "origin_managing_entity_name": 1,
          "fee_rate_na_cashless": 1,
          "commission_type_na_cashless": 1,
          "ho_no": 1,
          "connote_cancel": 1,
          "date_time_discount_calculation": 1,
          "flagging_discount_calculation": 1
      }
  };

  if (payload.column_type == "Unbilled") {
      listColumnGet = {
          "branch_id": 1,
          "awb_date": 1,
          "awb_number": 1,
          "customer_type": 1,
          "national_parent_id": 1,
          "national_parent_name": 1,
          "local_parent_id": 1,
          "local_parent_name": 1,
          "customer_id": 1,
          "customer_name": 1,
          "origin_branch_id": 1,
          "destination_branch_id": 1,
          "origin_sys_code": 1,
          "destination_sys_code": 1,
          "origin_zip_code_orion": 1,
          "destination_zip_code_orion": 1,
          "origin_id": 1,
          "origin_name": 1,
          "destination_id": 1,
          "destination_name": 1,
          "origin_zip_code_bms": 1,
          "destination_zip_code_bms": 1,
          "actual_weight": 1,
          "height": 1,
          "width": 1,
          "length": 1,
          "volumetric_weight_h_x_w_x_l": 1,
          "quantity": 1,
          "goods_type": 1,
          "goods_value": 1,
          "payment_type": 1,
          "connote_created_date_time": 1,
          "outbound_manifest_status": 1,
          "outbound_manifest_date_time": 1,
          "connote_outbound_manifested_by": 1,
          "handover_inbound_date_time": 1,
          "user_handover_inbound_data_entry": 1,
          "runsheet_created_date__time": 1,
          "final_connote_pod_status_date_time": 1,
          "final_connote_pod_created_by": 1,
          "final_pod_status_code": 1,
          "final_pod_status_name": 1,
          "service_type": 1,
          "original_amount_number": 1,
          "discount_amount_awb_number": 1,
          "adjusted_amount_number": 1,
          "packing_number": 1,
          "surcharge_number": 1,
          "other_charges_number": 1,
          "original_insurance_admin": 1,
          "original_insurance_premi": 1,
          "adjusted_insurance_premi_number": 1,
          "adjusted_insurance_admin_number": 1,
          "adjusted_insurance_premi_number": 1,
          "status_connote": 1,
          "total_amount_after_discount_charges_dpp": 1
      }
  };

  if (payload.column_type == "Unbilled") {
    listColumnGet = {
      "$awb_number": 1,
      "$awb_date": 1,
      "$branch_id": 1,
      "$customer_id": 1,
      "original_amount_number": {
              "$cond": {
                  "if": { "$eq": ["$original_amount_number", null] },
                  "then": "0",
                  "else": { "$toString": "$original_amount_number" }
              }
          },
          "surcharge_number": {
            "$cond": {
                "if": { "$eq": ["$surcharge_number", null] },
                "then": "0",
                "else": { "$toString": "$surcharge_number" }
            }
        },
        "packing_number": {
          "$cond": {
              "if": { "$eq": ["$packing_number", null] },
              "then": "0",
              "else": { "$toString": "$packing_number" }
          }
      },
      "other_charges_number": {
        "$cond": {
            "if": { "$eq": ["$other_charges_number", null] },
            "then": "0",
            "else": { "$toString": "$other_charges_number" }
        }
    },
    "discount_amount_awb_number": {
      "$cond": {
          "if": { "$eq": ["$discount_amount_awb_number", null] },
          "then": "0",
          "else": { "$toString": "$discount_amount_awb_number" }
      }
  },
  "adjusted_amount_number": {
    "$cond": {
        "if": { "$eq": ["$adjusted_amount_number", null] },
        "then": "0",
        "else": { "$toString": "$adjusted_amount_number" }
    }
},
      "$status_connote": 1,
      "$invoice_date": 1
    }
};
}
