var payload = [
  {
      "BANK ACCOUNT NUMBER": "9.80E+11",
      "BANK BRANCH NAME": "BRANCH",
      "BANK HOLDER NAME": "Penelope",
      "BANK NAME": "PT Bank CIMB Niaga TBK",
      "COST CENTER": "1.611.470.773.008",
      "COUNTRY": "Indonesia",
      "DIRECTORATE": "Strategy, Finance & SPAPM ID",
      "DS EMAIL": "kissbyglow@mailinator.com",
      "DS NAME": "Kiss by Glow",
      "DS NIP": "870002",
      "DS POSITION NAME": "870002-Head of PM",
      "Date of Birth": "30/09/66",
      "EMAIL ADDRESS": "penelope@mailinator.com",
      "EMPLOYEE CATEGORY": "Permanent",
      "EMPLOYEE NAME": "Pene Lope",
      "EMPLOYEE STATUS": "Active",
      "GENDER": "Female",
      "GRADE": "U10",
      "KTP": "2340000001",
      "LOCATION": "Kantor Pusat - Griya Niaga 1",
      "MARITAL STATUS": "Single",
      "NIP": "870001",
      "NPWP": "24300000001",
      "ORG LEVEL": "D1",
      "POSITION CODE": "870001-PM",
      "POSITION NAME": "870001-PM",
      "POSTAL CODE": "13720",
      "PROVINSI": "DKI Jakarta",
      "SUB DIRECTORATE": "Strategic Procurement & Admin Property Management ID",
      "TERMINATION DATE": "0",
      "TOWN OF BIRTH": "Sukabumi",
      "TOWN OR CITY": "Jakarta Timur"
  },
  {
      "BANK ACCOUNT NUMBER": "9.80E+11",
      "BANK BRANCH NAME": "BRANCH",
      "BANK HOLDER NAME": "Kiss ",
      "BANK NAME": "PT Bank CIMB Niaga TBK",
      "COST CENTER": "1.611.470.773.009",
      "COUNTRY": "Indonesia",
      "DIRECTORATE": "Strategy, Finance & SPAPM ID",
      "DS EMAIL": "",
      "DS NAME": "",
      "DS NIP": "",
      "DS POSITION NAME": "",
      "Date of Birth": "01/10/66",
      "EMAIL ADDRESS": "kissbyglow@mailinator.com",
      "EMPLOYEE CATEGORY": "Permanent",
      "EMPLOYEE NAME": "Kiss by Glow ",
      "EMPLOYEE STATUS": "Active",
      "GENDER": "Female",
      "GRADE": "U11",
      "KTP": "2340000002",
      "LOCATION": "Kantor Pusat - Griya Niaga 2",
      "MARITAL STATUS": "Single",
      "NIP": "870002",
      "NPWP": "24300000002",
      "ORG LEVEL": "D0",
      "POSITION CODE": "870002-Head of PM",
      "POSITION NAME": "870002-Head of PM",
      "POSTAL CODE": "13721",
      "PROVINSI": "DKI Jakarta",
      "SUB DIRECTORATE": "Strategic Procurement & Admin Property Management ID",
      "TERMINATION DATE": "1",
      "TOWN OF BIRTH": "Sukabumi",
      "TOWN OR CITY": "Jakarta Timur"
  },
  {
      "BANK ACCOUNT NUMBER": "9.80E+11",
      "BANK BRANCH NAME": "BRANCH",
      "BANK HOLDER NAME": "Mother ",
      "BANK NAME": "PT Bank CIMB Niaga TBK",
      "COST CENTER": "1.611.470.773.010",
      "COUNTRY": "Indonesia",
      "DIRECTORATE": "Strategy, Finance & SPAPM ID",
      "DS EMAIL": "kissbyglow@mailinator.com",
      "DS NAME": "Kiss by Glow",
      "DS NIP": "870002",
      "DS POSITION NAME": "870002-Head of PM",
      "Date of Birth": "02/10/66",
      "EMAIL ADDRESS": "motherofeart@mailinator.com",
      "EMPLOYEE CATEGORY": "Permanent",
      "EMPLOYEE NAME": "Mother of earth",
      "EMPLOYEE STATUS": "Active",
      "GENDER": "Female",
      "GRADE": "U12",
      "KTP": "2340000003",
      "LOCATION": "Kantor Pusat - Griya Niaga 3",
      "MARITAL STATUS": "Single",
      "NIP": "870003",
      "NPWP": "24300000003",
      "ORG LEVEL": "D2",
      "POSITION CODE": "870003-PM",
      "POSITION NAME": "870003-PM",
      "POSTAL CODE": "13722",
      "PROVINSI": "DKI Jakarta",
      "SUB DIRECTORATE": "Strategic Procurement & Admin Property Management ID",
      "TERMINATION DATE": "2",
      "TOWN OF BIRTH": "Sukabumi",
      "TOWN OR CITY": "Jakarta Timur"
  },
  {
      "BANK ACCOUNT NUMBER": "9.80E+11",
      "BANK BRANCH NAME": "BRANCH",
      "BANK HOLDER NAME": "Coconi",
      "BANK NAME": "PT Bank CIMB Niaga TBK",
      "COST CENTER": "1.611.470.773.011",
      "COUNTRY": "Indonesia",
      "DIRECTORATE": "Strategy, Finance & SPAPM ID",
      "DS EMAIL": "R.ditaruna@mailinator.com",
      "DS NAME": "R Satria Graha Ditaruna Ditaruna",
      "DS NIP": "870003",
      "DS POSITION NAME": "3030050-ERP & FAH Analyst and Maintenance Sr Specialist - 2",
      "Date of Birth": "03/10/66",
      "EMAIL ADDRESS": "coconi@mailinator.com",
      "EMPLOYEE CATEGORY": "Permanent",
      "EMPLOYEE NAME": "Coconi Bath",
      "EMPLOYEE STATUS": "Active",
      "GENDER": "Male",
      "GRADE": "U13",
      "KTP": "2340000004",
      "LOCATION": "Kantor Pusat - Griya Niaga 4",
      "MARITAL STATUS": "Married",
      "NIP": "870004",
      "NPWP": "24300000004",
      "ORG LEVEL": "D3",
      "POSITION CODE": "870004-ERP",
      "POSITION NAME": "870004-ERP",
      "POSTAL CODE": "13723",
      "PROVINSI": "DKI Jakarta",
      "SUB DIRECTORATE": "Strategic Procurement & Admin Property Management ID",
      "TERMINATION DATE": "3",
      "TOWN OF BIRTH": "Sukabumi",
      "TOWN OR CITY": "Jakarta Timur"
  },
  {
      "BANK ACCOUNT NUMBER": "9.80E+11",
      "BANK BRANCH NAME": "BRANCH",
      "BANK HOLDER NAME": "Nita",
      "BANK NAME": "PT Bank CIMB Niaga TBK",
      "COST CENTER": "1.611.470.773.012",
      "COUNTRY": "Indonesia",
      "DIRECTORATE": "Strategy, Finance & SPAPM ID",
      "DS EMAIL": "TKUNARKO@mailinator.com",
      "DS NAME": "Triko Kunarko",
      "DS NIP": "32144",
      "DS POSITION NAME": "Payment & Accounting Support Head",
      "Date of Birth": "04/10/66",
      "EMAIL ADDRESS": "Nita.Widyastuti@mailinator.com",
      "EMPLOYEE CATEGORY": "Permanent",
      "EMPLOYEE NAME": "Nita Widya",
      "EMPLOYEE STATUS": "Active",
      "GENDER": "Male",
      "GRADE": "U14",
      "KTP": "2340000005",
      "LOCATION": "Kantor Pusat - Griya Niaga 5",
      "MARITAL STATUS": "Married",
      "NIP": "32165",
      "NPWP": "24300000005",
      "ORG LEVEL": "D4",
      "POSITION CODE": "Accounting Support Sr Officer",
      "POSITION NAME": "Accounting Support Sr Officer",
      "POSTAL CODE": "13724",
      "PROVINSI": "DKI Jakarta",
      "SUB DIRECTORATE": "Strategic Procurement & Admin Property Management ID",
      "TERMINATION DATE": "4",
      "TOWN OF BIRTH": "Sukabumi",
      "TOWN OR CITY": "Jakarta Timur"
  }
];


console.log(payload.length);