var req = {
  candidate: {
    agama: "Islam",
    akreditasi_pendidikan_1: "A",
    akreditasi_pendidikan_2: "A",
    alamat_domisili:
      "Mid Plaza 2, Jl. Jenderal Sudirman No.4, Karet Tengsin, Kecamatan Tanah Abang, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10220",
    alamat_institusi_pendidikan_1:
      "Mid Plaza 2, Jl. Jenderal Sudirman No.4, Karet Tengsin, Kecamatan Tanah Abang, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10220",
    alamat_institusi_pendidikan_2:
      "Mid Plaza 2, Jl. Jenderal Sudirman No.4, Karet Tengsin, Kecamatan Tanah Abang, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10220",
    alamat_ktp:
      "Mid Plaza 2, Jl. Jenderal Sudirman No.4, Karet Tengsin, Kecamatan Tanah Abang, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10220",
    alamat_lembaga_pelatihan_1:
      "Mid Plaza 2, Jl. Jenderal Sudirman No.4, Karet Tengsin, Kecamatan Tanah Abang, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10220",
    alamat_lembaga_pelatihan_2:
      "Mid Plaza 2, Jl. Jenderal Sudirman No.4, Karet Tengsin, Kecamatan Tanah Abang, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10220",
    automation_id: "Z3NvcdLHUBNmMFvs",
    bahasa_1: "Indonesia",
    bahasa_2: "English",
    berat_badan: 60.5,
    bidang_organisasi_1: "magic",
    bidang_organisasi_2: "magic",
    bidang_pelatihan_1: "bahasa inggris",
    bidang_pelatihan_2: "english",
    bidang_perusahaan_pengalaman_1: "Saas",
    bidang_perusahaan_pengalaman_2: "Perbankan",
    bulan_akhir_organisasi_1: "Februari",
    bulan_akhir_organisasi_2: "Maret",
    bulan_akhir_perusahaan_1: "Oktober",
    bulan_akhir_perusahaan_2: "Januari",
    bulan_awal_organisasi_1: "September",
    bulan_awal_organisasi_2: "September",
    bulan_awal_perusahaan_1: "Agustus",
    bulan_awal_perusahaan_2: "September",
    company_id: 27414,
    created_at: 1757931946509,
    created_by: 0,
    email: "faqih@mailinator.com",
    email_blast_count: 0,
    email_blast_reason: " ",
    email_send_status: "MENUNGGU",
    fakultas_pendidikan_1: "Ilmu Komputer",
    fakultas_pendidikan_2: "Ilmu Komputer",
    file_ijazah_pendidikan_terakhir:
      "https://officeless-bpjs-prod-public.oss-ap-southeast-5.aliyuncs.com/27414/682992e40daa6-68241103380f2-document-pdf-companyID-27414-userCompanyID-187453-mtc0nze5ndexmzuxna%3D%3Dcd39309a0d36c279f928f68bf8d7f602-1747194113527-%285%29.pdf",
    file_sertifikasi_1:
      "https://officeless-bpjs-prod-public.oss-ap-southeast-5.aliyuncs.com/27414/681f458360221-Berita-Acara-Serah-Terima-%28BAST%29---BPJS-Ketenagakerjaan---Pengelolaan-Organisasi.pdf",
    file_sertifikasi_2:
      "https://officeless-bpjs-prod-public.oss-ap-southeast-5.aliyuncs.com/27414/681f4583ca662-Berita-Acara-Serah-Terima-%28BAST%29---BPJS-Ketenagakerjaan---Pengelolaan-Organisasi.pdf",
    first_name: "Muhammad",
    gaji_terakhir_perusahaan_1: 10000000,
    gaji_terakhir_perusahaan_2: 8000000,
    handphone_1: "08757547876",
    handphone_2: "85728202948",
    hubungan_kerabat_1: "Suami/Istri",
    hubungan_kerabat_2: "Saudara Tiri",
    hubungan_kerabat_3: "Kerabat",
    id: "SxKUuYCNS11BIYVv/110303/P/BEASISWA/JKS/150925",
    instansi_ayah: "Mekari",
    instansi_ibu: "Mekari",
    instansi_saudara_1: "UB",
    instansi_saudara_2: "SD",
    instansi_saudara_3: "TK",
    institusi_pendidikan_1: "Korea University",
    institusi_pendidikan_2: "Universitas Indonesia",
    ipk_pendidikan_1: "4",
    ipk_pendidikan_2: "3.31",
    is_difabel: "false",
    jabatan_akhir_perusahaan_1: "Quality Assurance",
    jabatan_akhir_perusahaan_2: "Quality Assurance",
    jabatan_awal_perusahaan_1: "Solution Engineer",
    jabatan_awal_perusahaan_2: "Quality Assurance",
    jabatan_organisasi_1: "ketua geng",
    jabatan_organisasi_2: "ketua suku",
    jenis_kelamin: "Laki-laki",
    jenis_kelamin_kerabat_1: "Perempuan",
    jenis_kelamin_kerabat_2: "Laki-laki",
    jenis_kelamin_kerabat_3: "",
    jenis_kelamin_saudara_1: "Laki-laki",
    jenis_kelamin_saudara_2: "Perempuan",
    jenis_kelamin_saudara_3: "Laki-laki",
    jenis_perusahaan_pengalaman_1: "PT",
    jenis_perusahaan_pengalaman_2: "PT",
    jenjang_pendidikan_1: "S1",
    jenjang_pendidikan_2: "S1",
    job_title_kerabat_2: "",
    jumlah_kantor_cabang_perusahaan_1: 100,
    jumlah_kantor_cabang_perusahaan_2: 100,
    jumlah_karyawan_perusahaan_1: 3000,
    jumlah_karyawan_perusahaan_2: 10000,
    jurusan_pendidikan_1: "Teknik Informatika",
    jurusan_pendidikan_2: "Teknik Informatika",
    kabupaten_domisili: "JAKARTA PUSAT",
    kabupaten_institusi_pendidikan_1: "JAKARTA PUSAT",
    kabupaten_institusi_pendidikan_2: "JAKARTA PUSAT",
    kabupaten_ktp: "JAKARTA PUSAT",
    kabupaten_lembaga_pelatihan_1: "JAKARTA PUSAT",
    kabupaten_lembaga_pelatihan_2: "JAKARTA PUSAT",
    kabupaten_toefl_ielts: "JAKARTA PUSAT",
    kode_pos_toefl_ielts: "10220",
    kode_registrasi: "SxKUuYCNS11BIYVv/110303/P/BEASISWA/JKS/150925",
    kodepos_domisili: "10220",
    kodepos_institusi_pendidikan_1: "10220",
    kodepos_institusi_pendidikan_2: "10220",
    kodepos_ktp: "10220",
    kodepos_lembaga_pelatihan_1: "10220",
    kodepos_lembaga_pelatihan_2: "10220",
    ktp_valid_until: 1767114000000,
    last_name: "Faqih",
    lembaga_pelatihan_1: "IDP",
    nama_ayah: "Ibnu",
    nama_ibu: "Suli",
    nama_kerabat_1: "Aulia Herdhyanti",
    nama_kerabat_2: "",
    nama_kerabat_3: "",
    nama_lembaga_toefl_ielts: "IDP",
    nama_lengkap: "Muhammad Faqih",
    nama_organisasi_1: "Organisasi Hitam",
    nama_organisasi_2: "Organisasi merah",
    nama_pelatihan_1: "IELTS",
    nama_pelatihan_2: "TOEFL",
    nama_saudara_1: "Hanum",
    nama_saudara_2: "putra",
    nama_saudara_3: "holi",
    nik: "5363636378987678",
    nilai_toefl_ielts: 80,
    no_ijazah_pendidikan_1: "ABC-152/72828-HAHA",
    no_ijazah_pendidikan_2: "ABC-152/72828-HAHA",
    no_kk: "73837372829",
    pekerjaan_ayah: "Wirausaha",
    pekerjaan_ibu: "Ibu Rumah Tangga",
    pekerjaan_saudara_1: "Mahasiswa",
    pekerjaan_saudara_2: "Siswa",
    pekerjaan_saudara_3: "TK",
    period_id: {
      id: "0dO3Vm3T3tQt",
      name: "Rekrutmen September 2025",
    },
    period_id_text: "0dO3Vm3T3tQt",
    pernah_toefl_ielts: "Ya, saya pernah ikut IELTS",
    perusahaan_pengalaman_1: "Perusahaan A",
    perusahaan_pengalaman_2: "Mandiri",
    photo_full_body:
      "https://officeless-bpjs-prod-public.oss-ap-southeast-5.aliyuncs.com/27414/682d734d2a1f7-foto_halfbody.jpg",
    photo_half_body:
      "https://officeless-bpjs-prod-public.oss-ap-southeast-5.aliyuncs.com/27414/682d734d2972d-foto-halfbody.jpg",
    photo_profile:
      "https://officeless-bpjs-prod-public.oss-ap-southeast-5.aliyuncs.com/27414/682aa4ad756b4-dummy.pdf",
    pipeline_id: {
      id: "wG0RyjItlnNzfIDZ",
      name: "DEFAULT",
    },
    provinsi_domisili: "DKI JAKARTA",
    provinsi_institusi_pendidikan_1: "DKI JAKARTA",
    provinsi_institusi_pendidikan_2: "DKI JAKARTA",
    provinsi_ktp: "DKI JAKARTA",
    provinsi_lembaga_pelatihan_1: "DKI JAKARTA",
    provinsi_lembaga_pelatihan_2: "ESQ",
    provinsi_toefl_ielts: "DKI JAKARTA",
    punya_kerabat_bpjs: "Ya, saya memiliki keluarga di BPJS Ketenagakerjaan",
    stage_detail: [],
    stage_id: {
      id: "lNRfnl0PLxI3iYk8",
      name: "Seleksi Administrasi",
    },
    stage_id_text: "lNRfnl0PLxI3iYk8",
    status_kawin: "Lajang",
    status_lulus_pendidikan_1: "Lulus",
    status_lulus_pendidikan_2: "Lulus",
    tahun_akhir_organisasi_1: 0,
    tahun_akhir_organisasi_2: 2024,
    tahun_akhir_perusahaan_1: 2025,
    tahun_akhir_perusahaan_2: 2024,
    tahun_awal_organisasi_1: 2020,
    tahun_awal_organisasi_2: 2021,
    tahun_awal_perusahaan_1: 2022,
    tahun_awal_perusahaan_2: 2024,
    tahun_mulai_pendidikan_1: 2020,
    tahun_mulai_pendidikan_2: 2024,
    tahun_pelatihan_1: "2025",
    tahun_pelatihan_2: "2024",
    tahun_selesai_pendidikan_1: 2024,
    tahun_selesai_pendidikan_2: 2025,
    tanggal_lahir: 1047315600000,
    tanggal_lahir_ayah: 652924800000,
    tanggal_lahir_ibu: 650160000000,
    tanggal_lahir_saudara_1: 971049600000,
    tanggal_lahir_saudara_2: 1254873600000,
    tanggal_lahir_saudara_3: 1094515200000,
    telepon: "6285728202948",
    telepon_toefl_ielts: "81293470099",
    tempat_lahir: "Jakarta",
    tgl_lahir_kerabat_1: 905385600000,
    tgl_lahir_kerabat_2: 1746057600000,
    tgl_lahir_kerabat_3: 991872000000,
    tinggi_badan: 160,
    tingkat_lisan_bahasa_1: "Sangat Baik",
    tingkat_lisan_bahasa_2: "Sedang",
    tingkat_membaca_bahasa_1: "Sangat Baik",
    tingkat_membaca_bahasa_2: "Sangat Baik",
    tingkat_mendengar_bahasa_1: "Sangat Baik",
    tingkat_mendengar_bahasa_2: "Sedang",
    tingkat_menulis_bahasa_1: "Sangat Baik",
    tingkat_menulis_bahasa_2: "Sangat Baik",
    tipe_lulusan_pendidikan_1: "Lulusan Dalam Negeri",
    tipe_lulusan_pendidikan_2: "Lulusan Dalam Negeri",
    unit_kerja_kerabat_1: "VAS",
    unit_kerja_kerabat_2: "",
    unit_kerja_kerabat_3: "",
    updated_at: 1757931946509,
    updated_by: 0,
    uraian_jabatan_perusahaan_1:
      "Quality Assurance (QA) bertanggung jawab untuk memastikan bahwa produk atau layanan yang dihasilkan memenuhi standar kualitas yang telah ditetapkan. QA melakukan pengujian, identifikasi cacat, serta memberikan masukan untuk perbaikan proses guna menjamin kepuasan pengguna dan keandalan sistem.",
    uraian_jabatan_perusahaan_2:
      "Quality Assurance (QA) bertanggung jawab untuk memastikan bahwa produk atau layanan yang dihasilkan memenuhi standar kualitas yang telah ditetapkan. QA melakukan pengujian, identifikasi cacat, serta memberikan masukan untuk perbaikan proses guna menjamin kepuasan pengguna dan keandalan sistem.",
    user_data_id_text: "SxKUuYCNS11BIYVv",
    user_id_text: "eVmC018YufzK6GLf",
    vacancy_id: "4tr7nNrO6lPg",
    vacancy_reference: "Kerabat / Teman",
  },
  stage: {
    company_id: 27414,
    created_at: 1748326566802,
    created_by: 178566,
    id: "7Jj9gT94LRjvd20Y",
    id_stage: "7Jj9gT94LRjvd20Y",
    is_hired: true,
    is_rejected: false,
    is_start: false,
    name: "Diterima",
    order: 3,
    pipeline_id_text: "qTuEAZkbQhlD3eD",
    updated_at: 1748326623258,
    updated_by: 178566,
  },
  trigger_by: 123456,
};

var vacancy = {
  id_vacancy: "4tr7nNrO6lPg",
  job_posting_id: {
    id: "2BZPzTe5ogLRYrKK",
    name: "System Analyst PTK Entry",
  },
  job_posting_name: "System Analyst PTK Entry",
};

var createLog = {
  "action": "candidate_to_employee_integration",
  "applied_job_position": "vacancy.job_posting_name",
  "approved_by": "",
  "candidate_email": "req.candidate.email",
  "candidate_id": "req.candidate.id",
  "candidate_name": "req.candidate.nama_lengkap",
  "created_at": "",
  "created_by": "",
  "employee_id": "",
  "employee_npk": "",
  "error_message": "message",
  "flow_status": "",
  "id_log": "",
  "is_hired": "req.stage.is_hired",
  "stage_id": "req.stage.id_stage",
  "stage_name": "req.stage.name",
  "status": "status",
  "triggered_by": "req.trigger_by",
  "updated_at": "",
  "updated_by": "",
  "vacancy_id": "req.candidate.vacancy_id"
};
