var project = {
  "BRANCH ID": "$branch_id",
  "CUSTOMER TYPE": "$customer_type",
  "CUSTOMER TYPE NAME": "$customer_type_name",
  "NATIONAL PARENT ID": "$national_parent_id",
  "NATIONAL PARENT ID NAME": "$national_parent_name",
  "LOCAL PARENT ID": "$local_parent_id",
  "LOCAL PARENT ID NAME": "$local_parent_name",
  "CUSTOMER ID": "$customer_id",
  "CUSTOMER NAME": "$customer_name",
  "TOTAL CONNOTE": "$total_all_connote",
  "TOTAL DPP": "$total_all_dpp",
  "TOTAL BILLED CONNOTE": "$total_billed_connote",
  "TOTAL DPP BILLED": "$total_billed_dpp",
  "TOTAL UNBILLED CONNOTE": "$total_unbilled_connote",
  "TOTAL DPP UNBILLED": "$total_unbilled_dpp",
  "UNBILLED TO TOTAL REVENUE RATIO (CONNOTE)": "$unbilled_to_total_revenue_ratio_connote",
  "UNBILLED TO TOTAL REVENUE RATIO (AMOUNT)": "$unbilled_to_total_revenue_ratio_amount",
  "POLARISASI": "$polarisasi",
  "TARGET": "$target",
  "ACTUAL": "$actual",
  '%ACTUAL': "$actual_percentage",
  '%ACHIEVEMENT': "$achievement"
};
